//! Runtime library code generation for QB64Fresh C backend.
//!
//! This module generates the inline runtime library declarations that provide
//! the core functionality for QB64Fresh programs: string handling, I/O operations,
//! math functions, and built-in QB64 functions.
//!
//! When `RuntimeMode::Inline` is selected, these functions are embedded directly
//! in the generated C code, making the output self-contained and portable.
//!
//! When `RuntimeMode::External` is selected, the generated code instead includes
//! a header file reference to link against the external runtime library.
//!
//! ## Module Organization
//!
//! The runtime is split into domain-specific submodules:
//! - `types` - String type definition and type size helpers
//! - `strings` - Core string operations and manipulation (LEFT$, MID$, etc.)
//! - `io` - PRINT and INPUT functions
//! - `math` - Mathematical functions and type conversions
//! - `file` - File I/O operations (OPEN, CLOSE, GET, PUT)
//! - `keyboard` - Keyboard input functions (INKEY$, _KEYHIT, etc.)
//! - `memory` - Memory functions (PEEK, POKE, VARPTR)
//! - `timing` - Timer and timing functions (TIMER, SLEEP, DATE$, TIME$)
//! - `arrays` - Array operations (LBOUND, UBOUND, REDIM)
//! - `audio` - Audio functions (_SNDPLAY, BEEP, SOUND)
//! - `graphics` - Graphics stubs (SCREEN, LINE, CIRCLE, etc.)
//! - `legacy` - Legacy DOS functions (DEF SEG, OUT, INP)
//! - `system` - System stubs (filesystem, shell, console)
//! - `error` - Error handling functions
//! - `debug` - Debug runtime support (breakpoints, stepping, IPC)

mod arrays;
mod audio;
pub mod debug;
mod error;
mod file;
mod graphics;
mod io;
mod keyboard;
mod legacy;
mod math;
mod memory;
mod strings;
mod system;
mod timing;
mod types;

use crate::codegen::error::CodeGenError;
use crate::writeln_code;

use super::RuntimeMode;

/// Emits the header section including runtime declarations.
///
/// This function writes the standard includes and either inline runtime code
/// or external library references based on the configured runtime mode.
///
/// # Arguments
///
/// * `output` - Output buffer to write to
/// * `runtime_mode` - Whether to inline or link external runtime
///
/// For debug support, use [`emit_header_with_debug`] instead.
#[allow(dead_code)]
pub(in crate::codegen) fn emit_header(
    output: &mut String,
    runtime_mode: RuntimeMode,
) -> Result<(), CodeGenError> {
    emit_header_with_debug(output, runtime_mode, false, None)
}

/// Emits the header section with optional debug support.
///
/// When `debug_enabled` is true, includes the debug runtime for breakpoints,
/// stepping, and debugger communication.
///
/// # Arguments
///
/// * `output` - Output buffer to write to
/// * `runtime_mode` - Whether to inline or link external runtime
/// * `debug_enabled` - Whether to include debug hooks
/// * `source_file` - The source file name (for debug line tracking)
pub(in crate::codegen) fn emit_header_with_debug(
    output: &mut String,
    runtime_mode: RuntimeMode,
    debug_enabled: bool,
    source_file: Option<&str>,
) -> Result<(), CodeGenError> {
    writeln_code!(output, "/* Generated by QB64Fresh */")?;

    // POSIX feature test macros - must come before any includes
    // These enable timespec, clock_gettime, usleep, etc. on POSIX systems
    writeln_code!(output, "#ifndef _WIN32")?;
    writeln_code!(output, "#define _POSIX_C_SOURCE 199309L")?;
    writeln_code!(output, "#define _DEFAULT_SOURCE")?;
    writeln_code!(output, "#endif")?;
    writeln_code!(output)?;

    writeln_code!(output, "#include <stdio.h>")?;
    writeln_code!(output, "#include <stdlib.h>")?;
    writeln_code!(output, "#include <stdint.h>")?;
    writeln_code!(output, "#include <stdbool.h>")?;
    writeln_code!(output, "#include <string.h>")?;
    writeln_code!(output, "#include <math.h>")?;
    writeln_code!(output, "#include <ctype.h>")?;
    writeln_code!(output, "#include <time.h>")?;
    writeln_code!(output)?;

    // Platform-specific includes for TIMER function
    writeln_code!(output, "#ifdef _WIN32")?;
    writeln_code!(output, "#include <windows.h>")?;
    writeln_code!(output, "#else")?;
    writeln_code!(output, "#include <sys/time.h>")?;
    writeln_code!(output, "#ifdef __GLIBC__")?;
    writeln_code!(output, "#include <malloc.h>  /* For malloc_trim */")?;
    writeln_code!(output, "#endif")?;
    writeln_code!(output, "#endif")?;
    writeln_code!(output)?;

    // QB64 built-in constants
    writeln_code!(output, "/* QB64 built-in constants */")?;
    writeln_code!(output, "#define _TRUE (-1)")?;
    writeln_code!(output, "#define _FALSE (0)")?;
    // Comparison result constants for _IIF
    writeln_code!(output, "#define _EQUAL (0)")?;
    writeln_code!(output, "#define _GREATER (1)")?;
    writeln_code!(output, "#define _LESS (-1)")?;
    // String constants (initialized after qb_string type is defined)
    // For external runtime, _STR_EMPTY will be redefined after including the header
    writeln_code!(output, "#define _STR_EMPTY (&_qbs_empty)")?;
    writeln_code!(output, "#define _STR_CRLF qb_string_new(\"\\r\\n\")")?;
    writeln_code!(output, "#define _STR_LF qb_string_new(\"\\n\")")?;
    writeln_code!(output, "#define _STR_CR qb_string_new(\"\\r\")")?;
    writeln_code!(output, "#define _CHR_QUOTE qb_string_new(\"\\\"\")")?;
    writeln_code!(output, "#define _CHR_HT qb_string_new(\"\\t\")")?;
    writeln_code!(output, "#define _CHR_LF qb_string_new(\"\\n\")")?;
    writeln_code!(output)?;

    emit_keyboard_constants(output)?;
    emit_ascii_constants(output)?;
    emit_chr_constants(output)?;

    // Graphics/font constants that can be used as no-arg function calls
    writeln_code!(
        output,
        "/* Graphics pseudo-variables (zero-arg functions) */"
    )?;
    writeln_code!(output, "#define _FONT qb_font_get()")?;
    writeln_code!(output)?;

    match runtime_mode {
        RuntimeMode::Inline => {
            // Inline runtime library declarations
            emit_runtime_declarations(output)?;
        }
        RuntimeMode::External => {
            // Use external runtime library
            writeln_code!(output, "#include \"qb64fresh_rt.h\"")?;
            writeln_code!(output)?;
            // Alias for compatibility with inline code style
            writeln_code!(output, "typedef QbString qb_string;")?;
            writeln_code!(output)?;
            writeln_code!(output, "/* Using external QB64Fresh runtime library */")?;
            writeln_code!(
                output,
                "/* Compile with: gcc -I<include_path> program.c -L<lib_path> -lqb64fresh_rt */"
            )?;
            writeln_code!(output)?;
            // Error handling variables only - functions are in runtime library
            // Only emit the static variables, not the functions (they're in libqb64fresh_rt.a)
            writeln_code!(
                output,
                "/* Error Handling Variables (functions in runtime library) */"
            )?;
            writeln_code!(output)?;
            writeln_code!(output, "static int32_t _qb_err = 0;")?;
            writeln_code!(output, "static int32_t _qb_erl = 0;")?;
            writeln_code!(output, "static void* _qb_error_handler = NULL;")?;
            writeln_code!(output, "static int _qb_error_resume_next = 0;")?;
            writeln_code!(output, "static void* _qb_error_line = NULL;")?;
            writeln_code!(output, "static int32_t _INCLERRORLINE = 0;")?;
            writeln_code!(output)?;
            // GOSUB stack and STRIG event ID - needed by generated code even with external runtime
            legacy::emit_gosub_stack(output)?;
            writeln_code!(output, "static uint32_t _qb_strig_event_id = 0;")?;
            writeln_code!(output)?;
            // Empty string constant - for external runtime, use qb_string_empty() function
            // We'll call it once and cache the result
            writeln_code!(output, "/* Empty string constant for external runtime */")?;
            writeln_code!(output, "static qb_string* _qbs_empty = NULL;")?;
            writeln_code!(output, "static void _init_qbs_empty(void) {{")?;
            writeln_code!(
                output,
                "    if (!_qbs_empty) _qbs_empty = qb_string_empty();"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // Redefine _STR_EMPTY to use the cached empty string
            writeln_code!(output, "#undef _STR_EMPTY")?;
            writeln_code!(
                output,
                "#define _STR_EMPTY (_qbs_empty ? _qbs_empty : (_init_qbs_empty(), _qbs_empty))"
            )?;
            writeln_code!(output)?;
            // Type size dummy variables - needed by generated code even with external runtime
            types::emit_type_size_dummies(output)?;
            writeln_code!(output)?;
            // Helper functions needed by generated code - simplified versions for external runtime
            writeln_code!(output, "/* Helper functions for external runtime */")?;
            writeln_code!(output)?;
            // qb_len_str - string length (use runtime library function)
            writeln_code!(output, "int32_t qb_len_str(qb_string* s) {{")?;
            writeln_code!(output, "    return s ? (int32_t)qb_string_len(s) : 0;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // Temporary string pool functions - no-ops for external runtime (strings managed by library)
            writeln_code!(output, "uint64_t qbs_tmp_base_get(void) {{ return 0; }}")?;
            writeln_code!(
                output,
                "void qbs_cleanup(uint64_t base, int dummy) {{ (void)base; (void)dummy; }}"
            )?;
            writeln_code!(output)?;
            // qb_mid_assign - MID$ assignment for external runtime
            // MID$(str$, start [, length]) = value$
            // Replaces up to 'length' characters starting at 'start' (1-based)
            // If length is -1, replace up to min(remaining length, value length)
            writeln_code!(
                output,
                "void qb_mid_assign(qb_string** target, int32_t start, int32_t length, qb_string* value) {{"
            )?;
            writeln_code!(output, "    if (!target || !*target || !value) return;")?;
            writeln_code!(output, "    qb_string* s = *target;")?;
            writeln_code!(output, "    size_t s_len = qb_string_len(s);")?;
            writeln_code!(
                output,
                "    if (start < 1 || (size_t)start > s_len) return;"
            )?;
            writeln_code!(output, "    size_t idx = (size_t)(start - 1);")?;
            writeln_code!(output, "    size_t max_len = s_len - idx;")?;
            writeln_code!(output, "    size_t replace_len;")?;
            writeln_code!(output, "    if (length < 0) {{")?;
            writeln_code!(output, "        size_t value_len = qb_string_len(value);")?;
            writeln_code!(
                output,
                "        replace_len = (value_len < max_len) ? value_len : max_len;"
            )?;
            writeln_code!(output, "    }} else {{")?;
            writeln_code!(
                output,
                "        replace_len = ((size_t)length < max_len) ? (size_t)length : max_len;"
            )?;
            writeln_code!(output, "        size_t value_len = qb_string_len(value);")?;
            writeln_code!(
                output,
                "        if (replace_len > value_len) replace_len = value_len;"
            )?;
            writeln_code!(output, "    }}")?;
            writeln_code!(
                output,
                "    // Build new string: left part + replacement + right part"
            )?;
            writeln_code!(
                output,
                "    qb_string* left_part = (idx > 0) ? qb_left(s, (int32_t)idx) : qb_string_empty();"
            )?;
            writeln_code!(
                output,
                "    qb_string* replace_part = (replace_len > 0) ? qb_left(value, (int32_t)replace_len) : qb_string_empty();"
            )?;
            writeln_code!(output, "    size_t right_start = idx + replace_len;")?;
            writeln_code!(
                output,
                "    qb_string* right_part = (right_start < s_len) ? qb_right(s, (int32_t)(s_len - right_start + 1)) : qb_string_empty();"
            )?;
            writeln_code!(
                output,
                "    qb_string* temp = qb_string_concat(left_part, replace_part);"
            )?;
            writeln_code!(
                output,
                "    qb_string* new_str = qb_string_concat(temp, right_part);"
            )?;
            writeln_code!(output, "    // Clean up temporary strings")?;
            writeln_code!(output, "    if (left_part) qb_string_release(left_part);")?;
            writeln_code!(
                output,
                "    if (replace_part) qb_string_release(replace_part);"
            )?;
            writeln_code!(output, "    if (right_part) qb_string_release(right_part);")?;
            writeln_code!(output, "    if (temp) qb_string_release(temp);")?;
            writeln_code!(output, "    // Release old target and set new string")?;
            writeln_code!(output, "    qb_string_release(*target);")?;
            writeln_code!(output, "    *target = new_str;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_instr2 - 2-argument INSTR (starts at beginning)
            writeln_code!(
                output,
                "int32_t qb_instr2(qb_string* s, qb_string* find) {{"
            )?;
            writeln_code!(output, "    return qb_instr(1, s, find);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_controlchr - control character function (signature matches inline runtime)
            // Note: Inline runtime has void qb_controlchr(int32_t state), but generated code may call it differently
            // For now, provide both forms
            writeln_code!(output, "int32_t qb_controlchr(int32_t code) {{")?;
            writeln_code!(
                output,
                "    return (code >= 0 && code <= 31) || code == 127;"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_file_open_legacy - legacy file open (for compatibility)
            // OPEN mode$, [#]filenum, filename[, reclen]
            // Converts legacy syntax to standard qb_file_open call
            writeln_code!(
                output,
                "void qb_file_open_legacy(int32_t fnum, const char* mode_char, const char* fname) {{"
            )?;
            writeln_code!(output, "    if (!mode_char || !fname) return;")?;
            writeln_code!(
                output,
                "    // Convert legacy mode character to standard mode string"
            )?;
            writeln_code!(output, "    const char* mode;")?;
            writeln_code!(output, "    switch (mode_char[0]) {{")?;
            writeln_code!(output, "        case 'I': case 'i': mode = \"r\"; break;")?;
            writeln_code!(output, "        case 'O': case 'o': mode = \"w\"; break;")?;
            writeln_code!(output, "        case 'A': case 'a': mode = \"a\"; break;")?;
            writeln_code!(output, "        case 'R': case 'r': mode = \"r+b\"; break;")?;
            writeln_code!(output, "        case 'B': case 'b': mode = \"r+b\"; break;")?;
            writeln_code!(output, "        default: mode = \"r\"; break;")?;
            writeln_code!(output, "    }}")?;
            writeln_code!(output, "    qb_file_open(fnum, fname, mode);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_ubound2 - 2-argument UBOUND function
            // Stub implementation - returns 0 for now
            // Proper implementation would require array metadata tracking
            writeln_code!(output, "int32_t qb_ubound2(void* arr, int32_t dim) {{")?;
            writeln_code!(output, "    (void)arr; (void)dim;")?;
            writeln_code!(output, "    return 0;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_mki - make integer (for CV functions)
            writeln_code!(output, "qb_string* qb_mki(int16_t n) {{")?;
            writeln_code!(output, "    uint8_t bytes[2];")?;
            writeln_code!(output, "    bytes[0] = (uint8_t)(n & 0xFF);")?;
            writeln_code!(output, "    bytes[1] = (uint8_t)((n >> 8) & 0xFF);")?;
            writeln_code!(output, "    return qb_string_from_bytes(bytes, 2);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_string_fill - STRING$(n, code) - provided by runtime library
            // qb_string_fill_str - STRING$(n, c$) - wrapper for when STRING$ is called with a string argument
            // This is a wrapper for when STRING$ is called with a string argument
            writeln_code!(
                output,
                "qb_string* qb_string_fill_str(int32_t n, qb_string* c) {{"
            )?;
            writeln_code!(
                output,
                "    if (!c || qb_string_len(c) == 0) return qb_string_empty();"
            )?;
            writeln_code!(output, "    const char* data = qb_string_data(c);")?;
            writeln_code!(output, "    int32_t char_code = (unsigned char)data[0];")?;
            writeln_code!(output, "    return qb_string_fill(n, char_code);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_string_fill_code - STRING$(n, code) - fill with ASCII code (alias for compatibility)
            writeln_code!(
                output,
                "qb_string* qb_string_fill_code(int32_t n, int32_t code) {{"
            )?;
            writeln_code!(output, "    return qb_string_fill(n, code);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_mid2 - 2-argument MID$ function (start only, no length)
            writeln_code!(output, "qb_string* qb_mid2(qb_string* s, int32_t start) {{")?;
            writeln_code!(output, "    return qb_mid(s, start, -1);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_asc2 - 2-argument ASC function (position)
            writeln_code!(output, "int32_t qb_asc2(qb_string* s, int32_t pos) {{")?;
            writeln_code!(
                output,
                "    if (!s || pos < 1 || pos > (int32_t)qb_string_len(s)) return 0;"
            )?;
            writeln_code!(output, "    const char* data = qb_string_data(s);")?;
            writeln_code!(output, "    return (unsigned char)data[pos - 1];")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_array_register - register array metadata (1D version)
            // Stub implementation - no-op for now
            // Proper implementation would track array bounds for UBOUND/LBOUND functions
            writeln_code!(
                output,
                "void qb_array_register(void* ptr, int32_t lower, int32_t upper) {{"
            )?;
            writeln_code!(output, "    (void)ptr; (void)lower; (void)upper;")?;
            writeln_code!(
                output,
                "    // Array metadata registration not yet implemented"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_ubound - return upper bound of array (first dimension)
            // Stub implementation - returns 0 for now
            // Proper implementation would require array metadata tracking
            writeln_code!(output, "int32_t qb_ubound(void* arr) {{")?;
            writeln_code!(output, "    (void)arr;")?;
            writeln_code!(output, "    return 0;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_cvl - unpack 4-byte string to 32-bit long
            writeln_code!(output, "int32_t qb_cvl(qb_string* s) {{")?;
            writeln_code!(output, "    if (!s || qb_string_len(s) < 4) return 0;")?;
            writeln_code!(output, "    const char* data = qb_string_data(s);")?;
            writeln_code!(output, "    int32_t result;")?;
            writeln_code!(output, "    memcpy(&result, data, 4);")?;
            writeln_code!(output, "    return result;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // Command line arguments - needed by COMMAND$ functions
            // Note: qb_init_args is provided by the runtime library
            // We only need the static variables for qb_command_n and qb_commandcount
            writeln_code!(output, "/* Command line arguments */")?;
            writeln_code!(output, "static int _qb_argc = 0;")?;
            writeln_code!(output, "static char** _qb_argv = NULL;")?;
            writeln_code!(output)?;
            // qb_command_n - COMMAND$(n) - get command line argument
            writeln_code!(output, "qb_string* qb_command_n(int64_t n) {{")?;
            writeln_code!(
                output,
                "    if (n < 0 || n >= _qb_argc || !_qb_argv) return qb_string_empty();"
            )?;
            writeln_code!(output, "    return qb_string_new(_qb_argv[n]);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_commandcount - _COMMANDCOUNT
            writeln_code!(output, "int64_t qb_commandcount(void) {{")?;
            writeln_code!(output, "    return _qb_argc - 1;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_fullpath - _FULLPATH$
            writeln_code!(output, "qb_string* qb_fullpath(qb_string* path) {{")?;
            writeln_code!(output, "    if (!path) return qb_string_empty();")?;
            writeln_code!(output, "    const char* path_str = qb_string_data(path);")?;
            writeln_code!(output, "    char* resolved = realpath(path_str, NULL);")?;
            writeln_code!(output, "    if (resolved) {{")?;
            writeln_code!(
                output,
                "        qb_string* result = qb_string_new(resolved);"
            )?;
            writeln_code!(output, "        free(resolved);")?;
            writeln_code!(output, "        return result;")?;
            writeln_code!(output, "    }}")?;
            writeln_code!(output, "    return qb_string_retain(path);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_str - STR$(n) - convert number to string
            writeln_code!(output, "qb_string* qb_str(double n) {{")?;
            writeln_code!(output, "    char buf[64];")?;
            writeln_code!(output, "    snprintf(buf, sizeof(buf), \" %g\", n);")?;
            writeln_code!(output, "    return qb_string_new(buf);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_asc_assign - ASC assignment (set character at position)
            // For opaque strings, we need to create a new string with the modified character
            writeln_code!(
                output,
                "void qb_asc_assign(qb_string** s, int32_t pos, int32_t ch) {{"
            )?;
            writeln_code!(
                output,
                "    if (!s || !*s || pos < 1 || pos > (int32_t)qb_string_len(*s)) return;"
            )?;
            writeln_code!(output, "    qb_string* old = *s;")?;
            writeln_code!(output, "    size_t len = qb_string_len(old);")?;
            writeln_code!(output, "    // Build new string: left + char + right")?;
            writeln_code!(
                output,
                "    qb_string* left = (pos > 1) ? qb_left(old, pos - 1) : qb_string_empty();"
            )?;
            writeln_code!(output, "    qb_string* char_str = qb_chr(ch);")?;
            writeln_code!(
                output,
                "    qb_string* right = (pos < (int32_t)len) ? qb_right(old, (int32_t)(len - pos + 1)) : qb_string_empty();"
            )?;
            writeln_code!(
                output,
                "    qb_string* temp = qb_string_concat(left, char_str);"
            )?;
            writeln_code!(
                output,
                "    qb_string* new_str = qb_string_concat(temp, right);"
            )?;
            writeln_code!(output, "    // Clean up")?;
            writeln_code!(output, "    if (left) qb_string_release(left);")?;
            writeln_code!(output, "    if (char_str) qb_string_release(char_str);")?;
            writeln_code!(output, "    if (right) qb_string_release(right);")?;
            writeln_code!(output, "    if (temp) qb_string_release(temp);")?;
            writeln_code!(output, "    qb_string_release(old);")?;
            writeln_code!(output, "    *s = new_str;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_shl - _SHL (shift left)
            writeln_code!(output, "int64_t qb_shl(int64_t value, int32_t shift) {{")?;
            writeln_code!(
                output,
                "    return shift >= 0 ? (value << shift) : (value >> (-shift));"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_file_get_string - GET # for strings (binary read into string buffer)
            writeln_code!(
                output,
                "void qb_file_get_string(int32_t fnum, qb_string* s) {{"
            )?;
            writeln_code!(output, "    if (!s) return;")?;
            writeln_code!(output, "    size_t len = qb_string_len(s);")?;
            writeln_code!(output, "    if (len == 0) return;")?;
            writeln_code!(
                output,
                "    // For external runtime, we need to use qb_file_get with the string's data"
            )?;
            writeln_code!(
                output,
                "    // Note: This assumes the string buffer is writable, which may not be true for opaque types"
            )?;
            writeln_code!(
                output,
                "    // For now, this is a stub - proper implementation requires runtime library support"
            )?;
            writeln_code!(output, "    (void)fnum; (void)s;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_array_register_md - multi-dimensional array registration
            // Stub implementation - no-op for now
            // Proper implementation would track array bounds for UBOUND/LBOUND functions
            writeln_code!(
                output,
                "void qb_array_register_md(void* ptr, int32_t num_dims, int32_t* lowers, int32_t* uppers) {{"
            )?;
            writeln_code!(
                output,
                "    (void)ptr; (void)num_dims; (void)lowers; (void)uppers;"
            )?;
            writeln_code!(
                output,
                "    // Multi-dimensional array metadata registration not yet implemented"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_environ - ENVIRON$ function
            writeln_code!(output, "qb_string* qb_environ(qb_string* name) {{")?;
            writeln_code!(output, "    if (!name) return qb_string_empty();")?;
            writeln_code!(output, "    const char* name_str = qb_string_data(name);")?;
            writeln_code!(output, "    const char* val = getenv(name_str);")?;
            writeln_code!(
                output,
                "    return val ? qb_string_new(val) : qb_string_empty();"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_cvi - unpack 2-byte string to 16-bit integer
            writeln_code!(output, "int16_t qb_cvi(qb_string* s) {{")?;
            writeln_code!(output, "    if (!s || qb_string_len(s) < 2) return 0;")?;
            writeln_code!(output, "    const char* data = qb_string_data(s);")?;
            writeln_code!(output, "    int16_t result;")?;
            writeln_code!(output, "    memcpy(&result, data, 2);")?;
            writeln_code!(output, "    return result;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_mkl - pack 32-bit long to 4-byte string
            writeln_code!(output, "qb_string* qb_mkl(int32_t n) {{")?;
            writeln_code!(output, "    uint8_t bytes[4];")?;
            writeln_code!(output, "    memcpy(bytes, &n, 4);")?;
            writeln_code!(output, "    return qb_string_from_bytes(bytes, 4);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_readfile - _READFILE$
            writeln_code!(output, "qb_string* qb_readfile(qb_string* path) {{")?;
            writeln_code!(output, "    if (!path) return qb_string_empty();")?;
            writeln_code!(output, "    const char* path_str = qb_string_data(path);")?;
            writeln_code!(output, "    FILE* f = fopen(path_str, \"rb\");")?;
            writeln_code!(output, "    if (!f) return qb_string_empty();")?;
            writeln_code!(output, "    fseek(f, 0, SEEK_END);")?;
            writeln_code!(output, "    long size = ftell(f);")?;
            writeln_code!(output, "    fseek(f, 0, SEEK_SET);")?;
            writeln_code!(output, "    char* buf = (char*)malloc(size + 1);")?;
            writeln_code!(
                output,
                "    if (!buf) {{ fclose(f); return qb_string_empty(); }}"
            )?;
            writeln_code!(output, "    fread(buf, 1, size, f);")?;
            writeln_code!(output, "    buf[size] = '\\0';")?;
            writeln_code!(output, "    fclose(f);")?;
            writeln_code!(
                output,
                "    qb_string* result = qb_string_from_bytes((uint8_t*)buf, size);"
            )?;
            writeln_code!(output, "    free(buf);")?;
            writeln_code!(output, "    return result;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_writefile - _WRITEFILE
            writeln_code!(
                output,
                "void qb_writefile(qb_string* path, qb_string* content) {{"
            )?;
            writeln_code!(output, "    if (!path || !content) return;")?;
            writeln_code!(output, "    const char* path_str = qb_string_data(path);")?;
            writeln_code!(
                output,
                "    const char* content_data = qb_string_data(content);"
            )?;
            writeln_code!(output, "    size_t content_len = qb_string_len(content);")?;
            writeln_code!(output, "    FILE* f = fopen(path_str, \"wb\");")?;
            writeln_code!(output, "    if (!f) return;")?;
            writeln_code!(output, "    fwrite(content_data, 1, content_len, f);")?;
            writeln_code!(output, "    fclose(f);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_deflate - compression (stub)
            writeln_code!(output, "qb_string* qb_deflate(qb_string* data) {{")?;
            writeln_code!(output, "    (void)data;")?;
            writeln_code!(output, "    return qb_string_empty();")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_red32, qb_green32, qb_blue32 - color component extraction
            writeln_code!(
                output,
                "int32_t qb_red32(uint32_t c) {{ return (c >> 16) & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_green32(uint32_t c) {{ return (c >> 8) & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_blue32(uint32_t c) {{ return c & 0xFF; }}"
            )?;
            writeln_code!(output)?;
            // qb_val_uint64 - VAL with UINT64 type
            writeln_code!(output, "uint64_t qb_val_uint64(qb_string* s) {{")?;
            writeln_code!(output, "    if (!s) return 0;")?;
            writeln_code!(output, "    const char* data = qb_string_data(s);")?;
            writeln_code!(output, "    return strtoull(data, NULL, 10);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_val_int64 - VAL with INT64 type
            writeln_code!(output, "int64_t qb_val_int64(qb_string* s) {{")?;
            writeln_code!(output, "    if (!s) return 0;")?;
            writeln_code!(output, "    const char* data = qb_string_data(s);")?;
            writeln_code!(output, "    return strtoll(data, NULL, 10);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_file_put_string - PUT # for strings (binary write from string buffer)
            writeln_code!(
                output,
                "void qb_file_put_string(int32_t fnum, qb_string* s) {{"
            )?;
            writeln_code!(output, "    if (!s) return;")?;
            writeln_code!(output, "    size_t len = qb_string_len(s);")?;
            writeln_code!(output, "    if (len == 0) return;")?;
            writeln_code!(output, "    const char* data = qb_string_data(s);")?;
            writeln_code!(output, "    qb_file_put(fnum, data, len);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_error - ERROR statement
            writeln_code!(output, "void qb_error(int32_t code) {{")?;
            writeln_code!(output, "    fprintf(stderr, \"ERROR %d\\n\", code);")?;
            writeln_code!(output, "    exit(code);")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_echo - ECHO statement (console output control)
            // ECHO ON/OFF controls whether INPUT prompts are displayed
            // Stub implementation - echo is always on for now
            writeln_code!(output, "void qb_echo(int32_t flag) {{")?;
            writeln_code!(output, "    (void)flag;")?;
            writeln_code!(
                output,
                "    // ECHO control not yet implemented in runtime library"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // qb_sgn - SGN function
            writeln_code!(output, "int32_t qb_sgn(double n) {{")?;
            writeln_code!(output, "    if (n > 0) return 1;")?;
            writeln_code!(output, "    if (n < 0) return -1;")?;
            writeln_code!(output, "    return 0;")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // Additional missing functions - batch add
            writeln_code!(
                output,
                "/* Additional stub functions for QB64PE compatibility */"
            )?;
            writeln_code!(output, "int32_t qb_icon(void) {{ return 0; }}")?;
            writeln_code!(output, "int32_t qb_acceptfiledrop(void) {{ return 0; }}")?;
            writeln_code!(
                output,
                "int32_t qb_alpha(uint32_t c, int32_t mode) {{ (void)mode; return (c >> 24) & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_alpha32(uint32_t c) {{ return (c >> 24) & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "double qb_arccot(double n) {{ return atan(1.0 / n); }}"
            )?;
            writeln_code!(
                output,
                "double qb_arccsc(double n) {{ return asin(1.0 / n); }}"
            )?;
            writeln_code!(
                output,
                "double qb_arcsec(double n) {{ return acos(1.0 / n); }}"
            )?;
            writeln_code!(output, "int32_t qb_backgroundcolor(void) {{ return 0; }}")?;
            writeln_code!(
                output,
                "int32_t qb_blue(uint32_t c, int32_t mode) {{ (void)mode; return c & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "double qb_clamp(double x, double min, double max) {{ if (x < min) return min; if (x > max) return max; return x; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_console(int32_t mode) {{ (void)mode; return 1; }}"
            )?;
            writeln_code!(output, "double qb_cot(double n) {{ return 1.0 / tan(n); }}")?;
            writeln_code!(
                output,
                "double qb_coth(double n) {{ return 1.0 / tanh(n); }}"
            )?;
            writeln_code!(output, "double qb_csc(double n) {{ return 1.0 / sin(n); }}")?;
            writeln_code!(
                output,
                "double qb_csch(double n) {{ return 1.0 / sinh(n); }}"
            )?;
            writeln_code!(output, "int32_t qb_csrlin(void) {{ return 1; }}")?;
            writeln_code!(
                output,
                "double qb_cvd(qb_string* s) {{ if (!s || qb_string_len(s) < 8) return 0.0; double result; memcpy(&result, qb_string_data(s), 8); return result; }}"
            )?;
            writeln_code!(
                output,
                "double qb_cvq(qb_string* s) {{ if (!s || qb_string_len(s) < 8) return 0.0; double result; memcpy(&result, qb_string_data(s), 8); return result; }}"
            )?;
            writeln_code!(
                output,
                "float qb_cvs(qb_string* s) {{ if (!s || qb_string_len(s) < 4) return 0.0f; float result; memcpy(&result, qb_string_data(s), 4); return result; }}"
            )?;
            writeln_code!(output, "int32_t qb_defaultcolor(void) {{ return 7; }}")?;
            writeln_code!(output, "void qb_def_seg(int32_t seg) {{ (void)seg; }}")?;
            writeln_code!(
                output,
                "qb_string* qb_droppedfile_str(int32_t index) {{ (void)index; return qb_string_empty(); }}"
            )?;
            writeln_code!(output, "int32_t qb_exit_state(void) {{ return 0; }}")?;
            writeln_code!(output, "void qb_finishdrop(void) {{ }}")?;
            writeln_code!(output, "void qb_gfx_resize(int32_t flag) {{ (void)flag; }}")?;
            writeln_code!(
                output,
                "int32_t qb_green(uint32_t c, int32_t mode) {{ (void)mode; return (c >> 8) & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_lbound(void* arr) {{ (void)arr; return 0; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_loadfont3(qb_string* path, int32_t size, qb_string* req) {{ (void)path; (void)size; (void)req; return 0; }}"
            )?;
            writeln_code!(output, "int32_t logical_drives(void) {{ return 0; }}")?;
            writeln_code!(output)?;
            // For external runtime, qb_sleep and qb_delay are provided by the runtime library
            // However, qb_limit (for _LIMIT statement) needs to be emitted as it's not in the library
            // Note: Do NOT call timing::emit_timing_functions() here - it would emit conflicting functions
            writeln_code!(
                output,
                "/* Frame rate limiter for _LIMIT statement (external runtime) */"
            )?;
            writeln_code!(output, "#ifndef _WIN32")?;
            writeln_code!(output, "#include <unistd.h>  /* For usleep */")?;
            writeln_code!(output, "#include <sys/time.h>  /* For gettimeofday */")?;
            writeln_code!(output, "#endif")?;
            writeln_code!(output, "static double qb_last_frame_time = 0.0;")?;
            writeln_code!(output)?;
            writeln_code!(output, "#ifdef _WIN32")?;
            writeln_code!(output, "static double qb_get_time_seconds(void) {{")?;
            writeln_code!(output, "    LARGE_INTEGER freq, count;")?;
            writeln_code!(output, "    QueryPerformanceFrequency(&freq);")?;
            writeln_code!(output, "    QueryPerformanceCounter(&count);")?;
            writeln_code!(
                output,
                "    return (double)count.QuadPart / (double)freq.QuadPart;"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output, "#else")?;
            writeln_code!(output, "static double qb_get_time_seconds(void) {{")?;
            writeln_code!(output, "    struct timeval tv;")?;
            writeln_code!(output, "    gettimeofday(&tv, NULL);")?;
            writeln_code!(
                output,
                "    return (double)tv.tv_sec + (double)tv.tv_usec / 1000000.0;"
            )?;
            writeln_code!(output, "}}")?;
            writeln_code!(output, "#endif")?;
            writeln_code!(output)?;
            writeln_code!(output, "void qb_limit(int fps) {{")?;
            writeln_code!(output, "    if (fps <= 0) return;")?;
            writeln_code!(output, "    double target_frame_time = 1.0 / (double)fps;")?;
            writeln_code!(output, "    double current_time = qb_get_time_seconds();")?;
            writeln_code!(output, "    if (qb_last_frame_time > 0.0) {{")?;
            writeln_code!(
                output,
                "        double elapsed = current_time - qb_last_frame_time;"
            )?;
            writeln_code!(
                output,
                "        double wait_time = target_frame_time - elapsed;"
            )?;
            writeln_code!(output, "        if (wait_time > 0.0) {{")?;
            writeln_code!(output, "#ifdef _WIN32")?;
            writeln_code!(output, "            Sleep((DWORD)(wait_time * 1000.0));")?;
            writeln_code!(output, "#else")?;
            writeln_code!(
                output,
                "            usleep((unsigned int)(wait_time * 1000000.0));"
            )?;
            writeln_code!(output, "#endif")?;
            writeln_code!(output, "        }}")?;
            writeln_code!(output, "    }}")?;
            writeln_code!(output, "    qb_last_frame_time = qb_get_time_seconds();")?;
            writeln_code!(output, "}}")?;
            writeln_code!(output)?;
            // Note: qb_strig_check_event and qb_strig_event_done are provided by the runtime library

            // Additional missing functions for QB64PE compatibility
            writeln_code!(output, "/* Additional QB64PE-specific functions */")?;
            writeln_code!(output, "double qb_sec(double n) {{ return 1.0 / cos(n); }}")?;
            writeln_code!(
                output,
                "double qb_sech(double n) {{ return 1.0 / cosh(n); }}"
            )?;
            writeln_code!(output, "int32_t qb_negate(int32_t n) {{ return -n; }}")?;
            writeln_code!(
                output,
                "int32_t qb_red(uint32_t c, int32_t mode) {{ (void)mode; return (c >> 16) & 0xFF; }}"
            )?;
            writeln_code!(
                output,
                "uint32_t qb__rgb(int32_t r, int32_t g, int32_t b, int32_t mode) {{ (void)r; (void)g; (void)b; (void)mode; return 0; }}"
            )?;
            writeln_code!(
                output,
                "uint32_t qb__rgba(int32_t r, int32_t g, int32_t b, int32_t a, int32_t mode) {{ (void)r; (void)g; (void)b; (void)a; (void)mode; return 0; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_messagebox4(qb_string* title, qb_string* message, int32_t type, int32_t icon) {{ (void)title; (void)message; (void)type; (void)icon; return 0; }}"
            )?;
            writeln_code!(
                output,
                "int64_t qb_timer_n(int32_t n) {{ (void)n; return 0; }}"
            )?;
            writeln_code!(
                output,
                "void qb_sub__font(int32_t handle) {{ (void)handle; }}"
            )?;
            writeln_code!(
                output,
                "void qb_sub__freefont(int32_t handle) {{ (void)handle; }}"
            )?;
            writeln_code!(
                output,
                "void qb_mapunicode(int32_t unicode_code, int32_t ascii_pos) {{ (void)unicode_code; (void)ascii_pos; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb__mapunicode1(int32_t code) {{ return code; }}"
            )?;
            writeln_code!(
                output,
                "void qb_sub__title(qb_string* title) {{ (void)title; }}"
            )?;
            writeln_code!(output, "int32_t qb_resize(void) {{ return 0; }}")?;
            writeln_code!(output, "int32_t qb_resizewidth(void) {{ return 80; }}")?;
            writeln_code!(output, "int32_t qb_resizeheight(void) {{ return 25; }}")?;
            writeln_code!(output, "int32_t qb_pos(int64_t n) {{ (void)n; return 0; }}")?;
            writeln_code!(
                output,
                "int32_t qb_screen(int32_t row, int32_t col) {{ (void)row; (void)col; return 32; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_screen3(int32_t mode, int32_t depth, int32_t flags) {{ (void)mode; (void)depth; (void)flags; return 0; }}"
            )?;
            writeln_code!(output, "int32_t qb_screenx(void) {{ return 0; }}")?;
            writeln_code!(output, "int32_t qb_screeny(void) {{ return 0; }}")?;
            writeln_code!(
                output,
                "int32_t qb_readbit(qb_string* s, int32_t pos) {{ (void)s; (void)pos; return 0; }}"
            )?;
            writeln_code!(
                output,
                "qb_string* qb_openfiledialog5(qb_string* title, qb_string* filter, qb_string* def, qb_string* opts, int32_t flags) {{ (void)title; (void)filter; (void)def; (void)opts; (void)flags; return qb_string_empty(); }}"
            )?;
            writeln_code!(
                output,
                "qb_string* qb_savefiledialog4(qb_string* title, qb_string* filter, qb_string* def, int32_t flags) {{ (void)title; (void)filter; (void)def; (void)flags; return qb_string_empty(); }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_statuscode(int32_t handle) {{ (void)handle; return 0; }}"
            )?;
            writeln_code!(
                output,
                "int32_t qb_shellhide(qb_string* cmd) {{ (void)cmd; return 0; }}"
            )?;
            writeln_code!(
                output,
                "void qb_sub_set_foreground_window(intptr_t hwnd) {{ (void)hwnd; }}"
            )?;
            // Note: qb_sub_setdependency is defined in QB64pe source, don't redefine here
            writeln_code!(
                output,
                "qb_string* qb_md5(qb_string* s) {{ (void)s; return qb_string_empty(); }}"
            )?;
            writeln_code!(
                output,
                "qb_string* qb_mkd(double n) {{ uint8_t bytes[8]; memcpy(bytes, &n, 8); return qb_string_from_bytes(bytes, 8); }}"
            )?;
            writeln_code!(
                output,
                "qb_string* qb_mkq(double n) {{ uint8_t bytes[8]; memcpy(bytes, &n, 8); return qb_string_from_bytes(bytes, 8); }}"
            )?;
            writeln_code!(
                output,
                "qb_string* qb_mks(float n) {{ uint8_t bytes[4]; memcpy(bytes, &n, 4); return qb_string_from_bytes(bytes, 4); }}"
            )?;
            writeln_code!(output, "int64_t qb_windowhasfocus(void) {{ return -1; }}")?;
            writeln_code!(
                output,
                "void qb_view_print(int32_t top, int32_t bottom) {{ (void)top; (void)bottom; }}"
            )?;
            writeln_code!(output, "int32_t qb_totaldroppedfiles(void) {{ return 0; }}")?;
            writeln_code!(output)?;
        }
    }

    // Debug runtime support (if enabled)
    if debug_enabled {
        debug::emit_debug_runtime(output)?;

        // Emit source file name constant for debug tracking
        if let Some(source) = source_file {
            writeln_code!(output, "/* Source file for debug tracking */")?;
            writeln_code!(
                output,
                "static const char* _qb_dbg_source_file = \"{}\";",
                source.replace('\\', "\\\\").replace('"', "\\\"")
            )?;
            writeln_code!(output)?;
        }
    }
    Ok(())
}

/// Emits keyboard scan code constants for _KEYHIT and _KEYDOWN.
fn emit_keyboard_constants(output: &mut String) -> Result<(), CodeGenError> {
    writeln_code!(output, "/* Keyboard constants */")?;
    writeln_code!(output, "#define _KEY_ESC (27)")?;
    writeln_code!(output, "#define _KEY_BACKSPACE (8)")?;
    writeln_code!(output, "#define _KEY_TAB (9)")?;
    writeln_code!(output, "#define _KEY_ENTER (13)")?;
    writeln_code!(output, "#define _KEY_UP (18432)")?;
    writeln_code!(output, "#define _KEY_DOWN (20480)")?;
    writeln_code!(output, "#define _KEY_LEFT (19200)")?;
    writeln_code!(output, "#define _KEY_RIGHT (19712)")?;
    writeln_code!(output, "#define _KEY_INSERT (20992)")?;
    writeln_code!(output, "#define _KEY_DELETE (21248)")?;
    writeln_code!(output, "#define _KEY_HOME (18176)")?;
    writeln_code!(output, "#define _KEY_END (20224)")?;
    writeln_code!(output, "#define _KEY_PAGEUP (18688)")?;
    writeln_code!(output, "#define _KEY_PAGEDOWN (20736)")?;
    writeln_code!(output, "#define _KEY_F1 (15104)")?;
    writeln_code!(output, "#define _KEY_F2 (15360)")?;
    writeln_code!(output, "#define _KEY_F3 (15616)")?;
    writeln_code!(output, "#define _KEY_F4 (15872)")?;
    writeln_code!(output, "#define _KEY_F5 (16128)")?;
    writeln_code!(output, "#define _KEY_F6 (16384)")?;
    writeln_code!(output, "#define _KEY_F7 (16640)")?;
    writeln_code!(output, "#define _KEY_F8 (16896)")?;
    writeln_code!(output, "#define _KEY_F9 (17152)")?;
    writeln_code!(output, "#define _KEY_F10 (17408)")?;
    writeln_code!(output, "#define _KEY_F11 (34048)")?;
    writeln_code!(output, "#define _KEY_F12 (34304)")?;
    writeln_code!(output, "#define _KEY_LSHIFT (100304)")?;
    writeln_code!(output, "#define _KEY_RSHIFT (100303)")?;
    writeln_code!(output, "#define _KEY_LCTRL (100306)")?;
    writeln_code!(output, "#define _KEY_RCTRL (100305)")?;
    writeln_code!(output, "#define _KEY_LALT (100308)")?;
    writeln_code!(output, "#define _KEY_RALT (100307)")?;
    writeln_code!(output, "#define _KEY_LAPPLE (100310)")?;
    writeln_code!(output, "#define _KEY_RAPPLE (100309)")?;
    writeln_code!(output)?;

    // Console destination constant
    writeln_code!(output, "/* Console constants */")?;
    writeln_code!(output, "#define _CONSOLE (-1)")?;
    writeln_code!(output)?;
    Ok(())
}

/// Emits ASCII value constants.
fn emit_ascii_constants(output: &mut String) -> Result<(), CodeGenError> {
    writeln_code!(output, "/* ASCII constants */")?;
    writeln_code!(output, "#define _ASC_NUL (0)")?;
    writeln_code!(output, "#define _ASC_SOH (1)")?;
    writeln_code!(output, "#define _ASC_STX (2)")?;
    writeln_code!(output, "#define _ASC_ETX (3)")?;
    writeln_code!(output, "#define _ASC_EOT (4)")?;
    writeln_code!(output, "#define _ASC_ENQ (5)")?;
    writeln_code!(output, "#define _ASC_ACK (6)")?;
    writeln_code!(output, "#define _ASC_BEL (7)")?;
    writeln_code!(output, "#define _ASC_BS (8)")?;
    writeln_code!(output, "#define _ASC_HT (9)")?;
    writeln_code!(output, "#define _ASC_LF (10)")?;
    writeln_code!(output, "#define _ASC_VT (11)")?;
    writeln_code!(output, "#define _ASC_FF (12)")?;
    writeln_code!(output, "#define _ASC_CR (13)")?;
    writeln_code!(output, "#define _ASC_SO (14)")?;
    writeln_code!(output, "#define _ASC_SI (15)")?;
    writeln_code!(output, "#define _ASC_DLE (16)")?;
    writeln_code!(output, "#define _ASC_DC1 (17)")?;
    writeln_code!(output, "#define _ASC_DC2 (18)")?;
    writeln_code!(output, "#define _ASC_DC3 (19)")?;
    writeln_code!(output, "#define _ASC_DC4 (20)")?;
    writeln_code!(output, "#define _ASC_NAK (21)")?;
    writeln_code!(output, "#define _ASC_SYN (22)")?;
    writeln_code!(output, "#define _ASC_ETB (23)")?;
    writeln_code!(output, "#define _ASC_CAN (24)")?;
    writeln_code!(output, "#define _ASC_EM (25)")?;
    writeln_code!(output, "#define _ASC_SUB (26)")?;
    writeln_code!(output, "#define _ASC_ESC (27)")?;
    writeln_code!(output, "#define _ASC_FS (28)")?;
    writeln_code!(output, "#define _ASC_GS (29)")?;
    writeln_code!(output, "#define _ASC_RS (30)")?;
    writeln_code!(output, "#define _ASC_US (31)")?;
    writeln_code!(output, "#define _ASC_SPACE (32)")?;
    writeln_code!(output, "#define _ASC_EXCLAMATION (33)")?;
    writeln_code!(output, "#define _ASC_QUOTE (34)")?;
    writeln_code!(output, "#define _ASC_HASH (35)")?;
    writeln_code!(output, "#define _ASC_DOLLAR (36)")?;
    writeln_code!(output, "#define _ASC_PERCENT (37)")?;
    writeln_code!(output, "#define _ASC_AMPERSAND (38)")?;
    writeln_code!(output, "#define _ASC_APOSTROPHE (39)")?;
    writeln_code!(output, "#define _ASC_LEFTBRACKET (40)")?;
    writeln_code!(output, "#define _ASC_RIGHTBRACKET (41)")?;
    writeln_code!(output, "#define _ASC_ASTERISK (42)")?;
    writeln_code!(output, "#define _ASC_PLUS (43)")?;
    writeln_code!(output, "#define _ASC_COMMA (44)")?;
    writeln_code!(output, "#define _ASC_MINUS (45)")?;
    writeln_code!(output, "#define _ASC_FULLSTOP (46)")?;
    writeln_code!(output, "#define _ASC_FORWARDSLASH (47)")?;
    writeln_code!(output, "#define _ASC_COLON (58)")?;
    writeln_code!(output, "#define _ASC_SEMICOLON (59)")?;
    writeln_code!(output, "#define _ASC_LESSTHAN (60)")?;
    writeln_code!(output, "#define _ASC_EQUAL (61)")?;
    writeln_code!(output, "#define _ASC_GREATERTHAN (62)")?;
    writeln_code!(output, "#define _ASC_QUESTION (63)")?;
    writeln_code!(output, "#define _ASC_ATSIGN (64)")?;
    writeln_code!(output, "#define _ASC_LEFTSQUAREBRACKET (91)")?;
    writeln_code!(output, "#define _ASC_BACKSLASH (92)")?;
    writeln_code!(output, "#define _ASC_RIGHTSQUAREBRACKET (93)")?;
    writeln_code!(output, "#define _ASC_CARET (94)")?;
    writeln_code!(output, "#define _ASC_UNDERSCORE (95)")?;
    writeln_code!(output, "#define _ASC_GRAVE (96)")?;
    writeln_code!(output, "#define _ASC_LEFTCURLYBRACKET (123)")?;
    writeln_code!(output, "#define _ASC_VERTICALBAR (124)")?;
    writeln_code!(output, "#define _ASC_RIGHTCURLYBRACKET (125)")?;
    writeln_code!(output, "#define _ASC_TILDE (126)")?;
    writeln_code!(output, "#define _ASC_DEL (127)")?;
    writeln_code!(output)?;
    Ok(())
}

/// Emits forward declarations for cross-module dependencies.
///
/// Some runtime functions reference variables or helper functions that are
/// defined in other modules. This function emits forward declarations to
/// ensure proper compilation order:
/// - `_qb_gfx_warn` - defined in graphics.rs, used by memory.rs
/// - `_qb_palette` - defined in legacy.rs, used by system.rs
fn emit_forward_declarations(output: &mut String) -> Result<(), CodeGenError> {
    writeln_code!(
        output,
        "/* Forward declarations for cross-module dependencies */"
    )?;

    // Graphics warning function (defined in graphics.rs, used by memory.rs and system.rs)
    writeln_code!(output, "static void _qb_gfx_warn(void);")?;

    // Graphics frame counter and init function (defined in graphics.rs, used by system.rs)
    writeln_code!(output, "static int _qb_gfx_frame_count;")?;
    writeln_code!(output, "static void _qb_gfx_init_max_frames(void);")?;

    // Palette array (defined in legacy.rs, used by system.rs)
    writeln_code!(output, "static uint32_t _qb_palette[256];")?;

    writeln_code!(output)?;
    Ok(())
}

/// Emits character string constants (as qb_string*).
fn emit_chr_constants(output: &mut String) -> Result<(), CodeGenError> {
    writeln_code!(output, "/* Character string constants */")?;
    writeln_code!(output, "#define _CHR_NUL qb_string_new(\"\\0\")")?;
    writeln_code!(output, "#define _CHR_SOH qb_string_new(\"\\x01\")")?;
    writeln_code!(output, "#define _CHR_STX qb_string_new(\"\\x02\")")?;
    writeln_code!(output, "#define _CHR_ETX qb_string_new(\"\\x03\")")?;
    writeln_code!(output, "#define _CHR_EOT qb_string_new(\"\\x04\")")?;
    writeln_code!(output, "#define _CHR_ENQ qb_string_new(\"\\x05\")")?;
    writeln_code!(output, "#define _CHR_ACK qb_string_new(\"\\x06\")")?;
    writeln_code!(output, "#define _CHR_BEL qb_string_new(\"\\x07\")")?;
    writeln_code!(output, "#define _CHR_BS qb_string_new(\"\\x08\")")?;
    writeln_code!(output, "#define _CHR_VT qb_string_new(\"\\x0B\")")?;
    writeln_code!(output, "#define _CHR_FF qb_string_new(\"\\x0C\")")?;
    writeln_code!(output, "#define _CHR_CR qb_string_new(\"\\r\")")?;
    writeln_code!(output, "#define _CHR_SO qb_string_new(\"\\x0E\")")?;
    writeln_code!(output, "#define _CHR_SI qb_string_new(\"\\x0F\")")?;
    writeln_code!(output, "#define _CHR_DLE qb_string_new(\"\\x10\")")?;
    writeln_code!(output, "#define _CHR_DC1 qb_string_new(\"\\x11\")")?;
    writeln_code!(output, "#define _CHR_DC2 qb_string_new(\"\\x12\")")?;
    writeln_code!(output, "#define _CHR_DC3 qb_string_new(\"\\x13\")")?;
    writeln_code!(output, "#define _CHR_DC4 qb_string_new(\"\\x14\")")?;
    writeln_code!(output, "#define _CHR_NAK qb_string_new(\"\\x15\")")?;
    writeln_code!(output, "#define _CHR_SYN qb_string_new(\"\\x16\")")?;
    writeln_code!(output, "#define _CHR_ETB qb_string_new(\"\\x17\")")?;
    writeln_code!(output, "#define _CHR_CAN qb_string_new(\"\\x18\")")?;
    writeln_code!(output, "#define _CHR_EM qb_string_new(\"\\x19\")")?;
    writeln_code!(output, "#define _CHR_SUB qb_string_new(\"\\x1A\")")?;
    writeln_code!(output, "#define _CHR_ESC qb_string_new(\"\\x1B\")")?;
    writeln_code!(output, "#define _CHR_FS qb_string_new(\"\\x1C\")")?;
    writeln_code!(output, "#define _CHR_GS qb_string_new(\"\\x1D\")")?;
    writeln_code!(output, "#define _CHR_RS qb_string_new(\"\\x1E\")")?;
    writeln_code!(output, "#define _CHR_US qb_string_new(\"\\x1F\")")?;
    writeln_code!(output, "#define _CHR_SPACE qb_string_new(\" \")")?;
    writeln_code!(output, "#define _CHR_EXCLAMATION qb_string_new(\"!\")")?;
    writeln_code!(output, "#define _CHR_HASH qb_string_new(\"#\")")?;
    writeln_code!(output, "#define _CHR_DOLLAR qb_string_new(\"$\")")?;
    writeln_code!(output, "#define _CHR_PERCENT qb_string_new(\"%\")")?;
    writeln_code!(output, "#define _CHR_AMPERSAND qb_string_new(\"&\")")?;
    writeln_code!(output, "#define _CHR_APOSTROPHE qb_string_new(\"'\")")?;
    writeln_code!(output, "#define _CHR_LEFTBRACKET qb_string_new(\"(\")")?;
    writeln_code!(output, "#define _CHR_RIGHTBRACKET qb_string_new(\")\")")?;
    writeln_code!(output, "#define _CHR_ASTERISK qb_string_new(\"*\")")?;
    writeln_code!(output, "#define _CHR_PLUS qb_string_new(\"+\")")?;
    writeln_code!(output, "#define _CHR_COMMA qb_string_new(\",\")")?;
    writeln_code!(output, "#define _CHR_MINUS qb_string_new(\"-\")")?;
    writeln_code!(output, "#define _CHR_FULLSTOP qb_string_new(\".\")")?;
    writeln_code!(output, "#define _CHR_FORWARDSLASH qb_string_new(\"/\")")?;
    writeln_code!(output, "#define _CHR_COLON qb_string_new(\":\")")?;
    writeln_code!(output, "#define _CHR_SEMICOLON qb_string_new(\";\")")?;
    writeln_code!(output, "#define _CHR_LESSTHAN qb_string_new(\"<\")")?;
    writeln_code!(output, "#define _CHR_EQUAL qb_string_new(\"=\")")?;
    writeln_code!(output, "#define _CHR_GREATERTHAN qb_string_new(\">\")")?;
    writeln_code!(output, "#define _CHR_QUESTION qb_string_new(\"?\")")?;
    writeln_code!(output, "#define _CHR_ATSIGN qb_string_new(\"@\")")?;
    writeln_code!(
        output,
        "#define _CHR_LEFTSQUAREBRACKET qb_string_new(\"[\")"
    )?;
    writeln_code!(output, "#define _CHR_BACKSLASH qb_string_new(\"\\\\\")")?;
    writeln_code!(
        output,
        "#define _CHR_RIGHTSQUAREBRACKET qb_string_new(\"]\")"
    )?;
    writeln_code!(output, "#define _CHR_CARET qb_string_new(\"^\")")?;
    writeln_code!(output, "#define _CHR_UNDERSCORE qb_string_new(\"_\")")?;
    writeln_code!(output, "#define _CHR_GRAVE qb_string_new(\"`\")")?;
    writeln_code!(
        output,
        "#define _CHR_LEFTCURLYBRACKET qb_string_new(\"{{\")"
    )?;
    writeln_code!(output, "#define _CHR_VERTICALBAR qb_string_new(\"|\")")?;
    writeln_code!(
        output,
        "#define _CHR_RIGHTCURLYBRACKET qb_string_new(\"}}\")"
    )?;
    writeln_code!(output, "#define _CHR_TILDE qb_string_new(\"~\")")?;
    writeln_code!(output, "#define _CHR_DEL qb_string_new(\"\\x7F\")")?;
    writeln_code!(output)?;
    Ok(())
}

/// Emits the complete inline runtime library declarations.
///
/// This includes:
/// - String type definition and operations (allocation, concatenation, comparison)
/// - PRINT functions for different types
/// - INPUT functions for user input
/// - Built-in string functions (LEN, CHR$, ASC, LEFT$, RIGHT$, MID$, etc.)
/// - Math helper functions (SGN, PI, RND, CLAMP)
fn emit_runtime_declarations(output: &mut String) -> Result<(), CodeGenError> {
    writeln_code!(output, "/* QB64Fresh Runtime Library */")?;
    writeln_code!(output)?;

    // Forward declarations for cross-module dependencies
    // These are defined later in graphics.rs and legacy.rs but used earlier
    emit_forward_declarations(output)?;

    types::emit_string_type(output)?;
    types::emit_type_size_dummies(output)?;
    strings::emit_temp_string_pool(output)?;
    strings::emit_string_functions(output)?;
    system::emit_stub_declarations(output)?;
    io::emit_print_functions(output)?;
    io::emit_input_functions(output)?;
    strings::emit_string_comparison(output)?;
    math::emit_builtin_functions(output)?;
    math::emit_math_functions(output)?;
    strings::emit_string_manipulation(output)?;
    io::emit_utility_functions(output)?;
    file::emit_file_io_functions(output)?;
    error::emit_error_handling(output)?;
    keyboard::emit_keyboard_functions(output)?;
    memory::emit_memory_functions(output)?;
    timing::emit_timing_functions(output)?;
    arrays::emit_array_functions(output)?;
    audio::emit_audio_functions(output)?;
    graphics::emit_graphics_stubs(output)?;
    legacy::emit_legacy_functions(output)?;
    legacy::emit_gosub_stack(output)?;
    Ok(())
}
