//! Runtime library code generation for QB64Fresh C backend.
//!
//! This module generates the inline runtime library declarations that provide
//! the core functionality for QB64Fresh programs: string handling, I/O operations,
//! math functions, and built-in QB64 functions.
//!
//! When `RuntimeMode::Inline` is selected, these functions are embedded directly
//! in the generated C code, making the output self-contained and portable.
//!
//! When `RuntimeMode::External` is selected, the generated code instead includes
//! a header file reference to link against the external runtime library.
//!
//! ## Module Organization
//!
//! The runtime is split into domain-specific submodules:
//! - `types` - String type definition and type size helpers
//! - `strings` - Core string operations and manipulation (LEFT$, MID$, etc.)
//! - `io` - PRINT and INPUT functions
//! - `math` - Mathematical functions and type conversions
//! - `file` - File I/O operations (OPEN, CLOSE, GET, PUT)
//! - `keyboard` - Keyboard input functions (INKEY$, _KEYHIT, etc.)
//! - `memory` - Memory functions (PEEK, POKE, VARPTR)
//! - `timing` - Timer and timing functions (TIMER, SLEEP, DATE$, TIME$)
//! - `arrays` - Array operations (LBOUND, UBOUND, REDIM)
//! - `audio` - Audio functions (_SNDPLAY, BEEP, SOUND)
//! - `graphics` - Graphics stubs (SCREEN, LINE, CIRCLE, etc.)
//! - `legacy` - Legacy DOS functions (DEF SEG, OUT, INP)
//! - `system` - System stubs (filesystem, shell, console)
//! - `error` - Error handling functions
//! - `debug` - Debug runtime support (breakpoints, stepping, IPC)

mod arrays;
mod audio;
pub mod debug;
mod error;
mod file;
mod graphics;
mod io;
mod keyboard;
mod legacy;
mod math;
mod memory;
mod strings;
mod system;
mod timing;
mod types;

use std::fmt::Write;

use super::RuntimeMode;

/// Emits the header section including runtime declarations.
///
/// This function writes the standard includes and either inline runtime code
/// or external library references based on the configured runtime mode.
///
/// # Arguments
///
/// * `output` - Output buffer to write to
/// * `runtime_mode` - Whether to inline or link external runtime
///
/// For debug support, use [`emit_header_with_debug`] instead.
#[allow(dead_code)]
pub(in crate::codegen) fn emit_header(output: &mut String, runtime_mode: RuntimeMode) {
    emit_header_with_debug(output, runtime_mode, false, None);
}

/// Emits the header section with optional debug support.
///
/// When `debug_enabled` is true, includes the debug runtime for breakpoints,
/// stepping, and debugger communication.
///
/// # Arguments
///
/// * `output` - Output buffer to write to
/// * `runtime_mode` - Whether to inline or link external runtime
/// * `debug_enabled` - Whether to include debug hooks
/// * `source_file` - The source file name (for debug line tracking)
pub(in crate::codegen) fn emit_header_with_debug(
    output: &mut String,
    runtime_mode: RuntimeMode,
    debug_enabled: bool,
    source_file: Option<&str>,
) {
    writeln!(output, "/* Generated by QB64Fresh */").unwrap();

    // POSIX feature test macros - must come before any includes
    // These enable timespec, clock_gettime, usleep, etc. on POSIX systems
    writeln!(output, "#ifndef _WIN32").unwrap();
    writeln!(output, "#define _POSIX_C_SOURCE 199309L").unwrap();
    writeln!(output, "#define _DEFAULT_SOURCE").unwrap();
    writeln!(output, "#endif").unwrap();
    writeln!(output).unwrap();

    writeln!(output, "#include <stdio.h>").unwrap();
    writeln!(output, "#include <stdlib.h>").unwrap();
    writeln!(output, "#include <stdint.h>").unwrap();
    writeln!(output, "#include <stdbool.h>").unwrap();
    writeln!(output, "#include <string.h>").unwrap();
    writeln!(output, "#include <math.h>").unwrap();
    writeln!(output, "#include <ctype.h>").unwrap();
    writeln!(output, "#include <time.h>").unwrap();
    writeln!(output).unwrap();

    // Platform-specific includes for TIMER function
    writeln!(output, "#ifdef _WIN32").unwrap();
    writeln!(output, "#include <windows.h>").unwrap();
    writeln!(output, "#else").unwrap();
    writeln!(output, "#include <sys/time.h>").unwrap();
    writeln!(output, "#endif").unwrap();
    writeln!(output).unwrap();

    // QB64 built-in constants
    writeln!(output, "/* QB64 built-in constants */").unwrap();
    writeln!(output, "#define _TRUE (-1)").unwrap();
    writeln!(output, "#define _FALSE (0)").unwrap();
    // Comparison result constants for _IIF
    writeln!(output, "#define _EQUAL (0)").unwrap();
    writeln!(output, "#define _GREATER (1)").unwrap();
    writeln!(output, "#define _LESS (-1)").unwrap();
    // String constants (initialized after qb_string type is defined)
    writeln!(output, "#define _STR_EMPTY qb_string_new(\"\")").unwrap();
    writeln!(output, "#define _STR_CRLF qb_string_new(\"\\r\\n\")").unwrap();
    writeln!(output, "#define _STR_LF qb_string_new(\"\\n\")").unwrap();
    writeln!(output, "#define _STR_CR qb_string_new(\"\\r\")").unwrap();
    writeln!(output, "#define _CHR_QUOTE qb_string_new(\"\\\"\")").unwrap();
    writeln!(output, "#define _CHR_HT qb_string_new(\"\\t\")").unwrap();
    writeln!(output, "#define _CHR_LF qb_string_new(\"\\n\")").unwrap();
    writeln!(output).unwrap();

    emit_keyboard_constants(output);
    emit_ascii_constants(output);
    emit_chr_constants(output);

    // Graphics/font constants that can be used as no-arg function calls
    writeln!(
        output,
        "/* Graphics pseudo-variables (zero-arg functions) */"
    )
    .unwrap();
    writeln!(output, "#define _FONT qb_font_get()").unwrap();
    writeln!(output).unwrap();

    match runtime_mode {
        RuntimeMode::Inline => {
            // Inline runtime library declarations
            emit_runtime_declarations(output);
        }
        RuntimeMode::External => {
            // Use external runtime library
            writeln!(output, "#include \"qb64fresh_rt.h\"").unwrap();
            writeln!(output).unwrap();
            // Alias for compatibility with inline code style
            writeln!(output, "typedef QbString qb_string;").unwrap();
            writeln!(output).unwrap();
            writeln!(output, "/* Using external QB64Fresh runtime library */").unwrap();
            writeln!(
                output,
                "/* Compile with: gcc -I<include_path> program.c -L<lib_path> -lqb64fresh_rt */"
            )
            .unwrap();
            writeln!(output).unwrap();
        }
    }

    // Debug runtime support (if enabled)
    if debug_enabled {
        debug::emit_debug_runtime(output);

        // Emit source file name constant for debug tracking
        if let Some(source) = source_file {
            writeln!(output, "/* Source file for debug tracking */").unwrap();
            writeln!(
                output,
                "static const char* _qb_dbg_source_file = \"{}\";",
                source.replace('\\', "\\\\").replace('"', "\\\"")
            )
            .unwrap();
            writeln!(output).unwrap();
        }
    }
}

/// Emits keyboard scan code constants for _KEYHIT and _KEYDOWN.
fn emit_keyboard_constants(output: &mut String) {
    writeln!(output, "/* Keyboard constants */").unwrap();
    writeln!(output, "#define _KEY_ESC (27)").unwrap();
    writeln!(output, "#define _KEY_BACKSPACE (8)").unwrap();
    writeln!(output, "#define _KEY_TAB (9)").unwrap();
    writeln!(output, "#define _KEY_ENTER (13)").unwrap();
    writeln!(output, "#define _KEY_UP (18432)").unwrap();
    writeln!(output, "#define _KEY_DOWN (20480)").unwrap();
    writeln!(output, "#define _KEY_LEFT (19200)").unwrap();
    writeln!(output, "#define _KEY_RIGHT (19712)").unwrap();
    writeln!(output, "#define _KEY_INSERT (20992)").unwrap();
    writeln!(output, "#define _KEY_DELETE (21248)").unwrap();
    writeln!(output, "#define _KEY_HOME (18176)").unwrap();
    writeln!(output, "#define _KEY_END (20224)").unwrap();
    writeln!(output, "#define _KEY_PAGEUP (18688)").unwrap();
    writeln!(output, "#define _KEY_PAGEDOWN (20736)").unwrap();
    writeln!(output, "#define _KEY_F1 (15104)").unwrap();
    writeln!(output, "#define _KEY_F2 (15360)").unwrap();
    writeln!(output, "#define _KEY_F3 (15616)").unwrap();
    writeln!(output, "#define _KEY_F4 (15872)").unwrap();
    writeln!(output, "#define _KEY_F5 (16128)").unwrap();
    writeln!(output, "#define _KEY_F6 (16384)").unwrap();
    writeln!(output, "#define _KEY_F7 (16640)").unwrap();
    writeln!(output, "#define _KEY_F8 (16896)").unwrap();
    writeln!(output, "#define _KEY_F9 (17152)").unwrap();
    writeln!(output, "#define _KEY_F10 (17408)").unwrap();
    writeln!(output, "#define _KEY_F11 (34048)").unwrap();
    writeln!(output, "#define _KEY_F12 (34304)").unwrap();
    writeln!(output, "#define _KEY_LSHIFT (100304)").unwrap();
    writeln!(output, "#define _KEY_RSHIFT (100303)").unwrap();
    writeln!(output, "#define _KEY_LCTRL (100306)").unwrap();
    writeln!(output, "#define _KEY_RCTRL (100305)").unwrap();
    writeln!(output, "#define _KEY_LALT (100308)").unwrap();
    writeln!(output, "#define _KEY_RALT (100307)").unwrap();
    writeln!(output, "#define _KEY_LAPPLE (100310)").unwrap();
    writeln!(output, "#define _KEY_RAPPLE (100309)").unwrap();
    writeln!(output).unwrap();

    // Console destination constant
    writeln!(output, "/* Console constants */").unwrap();
    writeln!(output, "#define _CONSOLE (-1)").unwrap();
    writeln!(output).unwrap();
}

/// Emits ASCII value constants.
fn emit_ascii_constants(output: &mut String) {
    writeln!(output, "/* ASCII constants */").unwrap();
    writeln!(output, "#define _ASC_NUL (0)").unwrap();
    writeln!(output, "#define _ASC_SOH (1)").unwrap();
    writeln!(output, "#define _ASC_STX (2)").unwrap();
    writeln!(output, "#define _ASC_ETX (3)").unwrap();
    writeln!(output, "#define _ASC_EOT (4)").unwrap();
    writeln!(output, "#define _ASC_ENQ (5)").unwrap();
    writeln!(output, "#define _ASC_ACK (6)").unwrap();
    writeln!(output, "#define _ASC_BEL (7)").unwrap();
    writeln!(output, "#define _ASC_BS (8)").unwrap();
    writeln!(output, "#define _ASC_HT (9)").unwrap();
    writeln!(output, "#define _ASC_LF (10)").unwrap();
    writeln!(output, "#define _ASC_VT (11)").unwrap();
    writeln!(output, "#define _ASC_FF (12)").unwrap();
    writeln!(output, "#define _ASC_CR (13)").unwrap();
    writeln!(output, "#define _ASC_SO (14)").unwrap();
    writeln!(output, "#define _ASC_SI (15)").unwrap();
    writeln!(output, "#define _ASC_DLE (16)").unwrap();
    writeln!(output, "#define _ASC_DC1 (17)").unwrap();
    writeln!(output, "#define _ASC_DC2 (18)").unwrap();
    writeln!(output, "#define _ASC_DC3 (19)").unwrap();
    writeln!(output, "#define _ASC_DC4 (20)").unwrap();
    writeln!(output, "#define _ASC_NAK (21)").unwrap();
    writeln!(output, "#define _ASC_SYN (22)").unwrap();
    writeln!(output, "#define _ASC_ETB (23)").unwrap();
    writeln!(output, "#define _ASC_CAN (24)").unwrap();
    writeln!(output, "#define _ASC_EM (25)").unwrap();
    writeln!(output, "#define _ASC_SUB (26)").unwrap();
    writeln!(output, "#define _ASC_ESC (27)").unwrap();
    writeln!(output, "#define _ASC_FS (28)").unwrap();
    writeln!(output, "#define _ASC_GS (29)").unwrap();
    writeln!(output, "#define _ASC_RS (30)").unwrap();
    writeln!(output, "#define _ASC_US (31)").unwrap();
    writeln!(output, "#define _ASC_SPACE (32)").unwrap();
    writeln!(output, "#define _ASC_EXCLAMATION (33)").unwrap();
    writeln!(output, "#define _ASC_QUOTE (34)").unwrap();
    writeln!(output, "#define _ASC_HASH (35)").unwrap();
    writeln!(output, "#define _ASC_DOLLAR (36)").unwrap();
    writeln!(output, "#define _ASC_PERCENT (37)").unwrap();
    writeln!(output, "#define _ASC_AMPERSAND (38)").unwrap();
    writeln!(output, "#define _ASC_APOSTROPHE (39)").unwrap();
    writeln!(output, "#define _ASC_LEFTBRACKET (40)").unwrap();
    writeln!(output, "#define _ASC_RIGHTBRACKET (41)").unwrap();
    writeln!(output, "#define _ASC_ASTERISK (42)").unwrap();
    writeln!(output, "#define _ASC_PLUS (43)").unwrap();
    writeln!(output, "#define _ASC_COMMA (44)").unwrap();
    writeln!(output, "#define _ASC_MINUS (45)").unwrap();
    writeln!(output, "#define _ASC_FULLSTOP (46)").unwrap();
    writeln!(output, "#define _ASC_FORWARDSLASH (47)").unwrap();
    writeln!(output, "#define _ASC_COLON (58)").unwrap();
    writeln!(output, "#define _ASC_SEMICOLON (59)").unwrap();
    writeln!(output, "#define _ASC_LESSTHAN (60)").unwrap();
    writeln!(output, "#define _ASC_EQUAL (61)").unwrap();
    writeln!(output, "#define _ASC_GREATERTHAN (62)").unwrap();
    writeln!(output, "#define _ASC_QUESTION (63)").unwrap();
    writeln!(output, "#define _ASC_ATSIGN (64)").unwrap();
    writeln!(output, "#define _ASC_LEFTSQUAREBRACKET (91)").unwrap();
    writeln!(output, "#define _ASC_BACKSLASH (92)").unwrap();
    writeln!(output, "#define _ASC_RIGHTSQUAREBRACKET (93)").unwrap();
    writeln!(output, "#define _ASC_CARET (94)").unwrap();
    writeln!(output, "#define _ASC_UNDERSCORE (95)").unwrap();
    writeln!(output, "#define _ASC_GRAVE (96)").unwrap();
    writeln!(output, "#define _ASC_LEFTCURLYBRACKET (123)").unwrap();
    writeln!(output, "#define _ASC_VERTICALBAR (124)").unwrap();
    writeln!(output, "#define _ASC_RIGHTCURLYBRACKET (125)").unwrap();
    writeln!(output, "#define _ASC_TILDE (126)").unwrap();
    writeln!(output, "#define _ASC_DEL (127)").unwrap();
    writeln!(output).unwrap();
}

/// Emits forward declarations for cross-module dependencies.
///
/// Some runtime functions reference variables or helper functions that are
/// defined in other modules. This function emits forward declarations to
/// ensure proper compilation order:
/// - `_qb_gfx_warn` - defined in graphics.rs, used by memory.rs
/// - `_qb_palette` - defined in legacy.rs, used by system.rs
fn emit_forward_declarations(output: &mut String) {
    writeln!(
        output,
        "/* Forward declarations for cross-module dependencies */"
    )
    .unwrap();

    // Graphics warning function (defined in graphics.rs, used by memory.rs and system.rs)
    writeln!(output, "static void _qb_gfx_warn(void);").unwrap();

    // Graphics frame counter and init function (defined in graphics.rs, used by system.rs)
    writeln!(output, "static int _qb_gfx_frame_count;").unwrap();
    writeln!(output, "static void _qb_gfx_init_max_frames(void);").unwrap();

    // Palette array (defined in legacy.rs, used by system.rs)
    writeln!(output, "static uint32_t _qb_palette[256];").unwrap();

    writeln!(output).unwrap();
}

/// Emits character string constants (as qb_string*).
fn emit_chr_constants(output: &mut String) {
    writeln!(output, "/* Character string constants */").unwrap();
    writeln!(output, "#define _CHR_NUL qb_string_new(\"\\0\")").unwrap();
    writeln!(output, "#define _CHR_SOH qb_string_new(\"\\x01\")").unwrap();
    writeln!(output, "#define _CHR_STX qb_string_new(\"\\x02\")").unwrap();
    writeln!(output, "#define _CHR_ETX qb_string_new(\"\\x03\")").unwrap();
    writeln!(output, "#define _CHR_EOT qb_string_new(\"\\x04\")").unwrap();
    writeln!(output, "#define _CHR_ENQ qb_string_new(\"\\x05\")").unwrap();
    writeln!(output, "#define _CHR_ACK qb_string_new(\"\\x06\")").unwrap();
    writeln!(output, "#define _CHR_BEL qb_string_new(\"\\x07\")").unwrap();
    writeln!(output, "#define _CHR_BS qb_string_new(\"\\x08\")").unwrap();
    writeln!(output, "#define _CHR_VT qb_string_new(\"\\x0B\")").unwrap();
    writeln!(output, "#define _CHR_FF qb_string_new(\"\\x0C\")").unwrap();
    writeln!(output, "#define _CHR_CR qb_string_new(\"\\r\")").unwrap();
    writeln!(output, "#define _CHR_SO qb_string_new(\"\\x0E\")").unwrap();
    writeln!(output, "#define _CHR_SI qb_string_new(\"\\x0F\")").unwrap();
    writeln!(output, "#define _CHR_DLE qb_string_new(\"\\x10\")").unwrap();
    writeln!(output, "#define _CHR_DC1 qb_string_new(\"\\x11\")").unwrap();
    writeln!(output, "#define _CHR_DC2 qb_string_new(\"\\x12\")").unwrap();
    writeln!(output, "#define _CHR_DC3 qb_string_new(\"\\x13\")").unwrap();
    writeln!(output, "#define _CHR_DC4 qb_string_new(\"\\x14\")").unwrap();
    writeln!(output, "#define _CHR_NAK qb_string_new(\"\\x15\")").unwrap();
    writeln!(output, "#define _CHR_SYN qb_string_new(\"\\x16\")").unwrap();
    writeln!(output, "#define _CHR_ETB qb_string_new(\"\\x17\")").unwrap();
    writeln!(output, "#define _CHR_CAN qb_string_new(\"\\x18\")").unwrap();
    writeln!(output, "#define _CHR_EM qb_string_new(\"\\x19\")").unwrap();
    writeln!(output, "#define _CHR_SUB qb_string_new(\"\\x1A\")").unwrap();
    writeln!(output, "#define _CHR_ESC qb_string_new(\"\\x1B\")").unwrap();
    writeln!(output, "#define _CHR_FS qb_string_new(\"\\x1C\")").unwrap();
    writeln!(output, "#define _CHR_GS qb_string_new(\"\\x1D\")").unwrap();
    writeln!(output, "#define _CHR_RS qb_string_new(\"\\x1E\")").unwrap();
    writeln!(output, "#define _CHR_US qb_string_new(\"\\x1F\")").unwrap();
    writeln!(output, "#define _CHR_SPACE qb_string_new(\" \")").unwrap();
    writeln!(output, "#define _CHR_EXCLAMATION qb_string_new(\"!\")").unwrap();
    writeln!(output, "#define _CHR_HASH qb_string_new(\"#\")").unwrap();
    writeln!(output, "#define _CHR_DOLLAR qb_string_new(\"$\")").unwrap();
    writeln!(output, "#define _CHR_PERCENT qb_string_new(\"%\")").unwrap();
    writeln!(output, "#define _CHR_AMPERSAND qb_string_new(\"&\")").unwrap();
    writeln!(output, "#define _CHR_APOSTROPHE qb_string_new(\"'\")").unwrap();
    writeln!(output, "#define _CHR_LEFTBRACKET qb_string_new(\"(\")").unwrap();
    writeln!(output, "#define _CHR_RIGHTBRACKET qb_string_new(\")\")").unwrap();
    writeln!(output, "#define _CHR_ASTERISK qb_string_new(\"*\")").unwrap();
    writeln!(output, "#define _CHR_PLUS qb_string_new(\"+\")").unwrap();
    writeln!(output, "#define _CHR_COMMA qb_string_new(\",\")").unwrap();
    writeln!(output, "#define _CHR_MINUS qb_string_new(\"-\")").unwrap();
    writeln!(output, "#define _CHR_FULLSTOP qb_string_new(\".\")").unwrap();
    writeln!(output, "#define _CHR_FORWARDSLASH qb_string_new(\"/\")").unwrap();
    writeln!(output, "#define _CHR_COLON qb_string_new(\":\")").unwrap();
    writeln!(output, "#define _CHR_SEMICOLON qb_string_new(\";\")").unwrap();
    writeln!(output, "#define _CHR_LESSTHAN qb_string_new(\"<\")").unwrap();
    writeln!(output, "#define _CHR_EQUAL qb_string_new(\"=\")").unwrap();
    writeln!(output, "#define _CHR_GREATERTHAN qb_string_new(\">\")").unwrap();
    writeln!(output, "#define _CHR_QUESTION qb_string_new(\"?\")").unwrap();
    writeln!(output, "#define _CHR_ATSIGN qb_string_new(\"@\")").unwrap();
    writeln!(
        output,
        "#define _CHR_LEFTSQUAREBRACKET qb_string_new(\"[\")"
    )
    .unwrap();
    writeln!(output, "#define _CHR_BACKSLASH qb_string_new(\"\\\\\")").unwrap();
    writeln!(
        output,
        "#define _CHR_RIGHTSQUAREBRACKET qb_string_new(\"]\")"
    )
    .unwrap();
    writeln!(output, "#define _CHR_CARET qb_string_new(\"^\")").unwrap();
    writeln!(output, "#define _CHR_UNDERSCORE qb_string_new(\"_\")").unwrap();
    writeln!(output, "#define _CHR_GRAVE qb_string_new(\"`\")").unwrap();
    writeln!(
        output,
        "#define _CHR_LEFTCURLYBRACKET qb_string_new(\"{{\")"
    )
    .unwrap();
    writeln!(output, "#define _CHR_VERTICALBAR qb_string_new(\"|\")").unwrap();
    writeln!(
        output,
        "#define _CHR_RIGHTCURLYBRACKET qb_string_new(\"}}\")"
    )
    .unwrap();
    writeln!(output, "#define _CHR_TILDE qb_string_new(\"~\")").unwrap();
    writeln!(output, "#define _CHR_DEL qb_string_new(\"\\x7F\")").unwrap();
    writeln!(output).unwrap();
}

/// Emits the complete inline runtime library declarations.
///
/// This includes:
/// - String type definition and operations (allocation, concatenation, comparison)
/// - PRINT functions for different types
/// - INPUT functions for user input
/// - Built-in string functions (LEN, CHR$, ASC, LEFT$, RIGHT$, MID$, etc.)
/// - Math helper functions (SGN, PI, RND, CLAMP)
fn emit_runtime_declarations(output: &mut String) {
    writeln!(output, "/* QB64Fresh Runtime Library */").unwrap();
    writeln!(output).unwrap();

    // Forward declarations for cross-module dependencies
    // These are defined later in graphics.rs and legacy.rs but used earlier
    emit_forward_declarations(output);

    types::emit_string_type(output);
    types::emit_type_size_dummies(output);
    strings::emit_string_functions(output);
    system::emit_stub_declarations(output);
    io::emit_print_functions(output);
    io::emit_input_functions(output);
    strings::emit_string_comparison(output);
    math::emit_builtin_functions(output);
    math::emit_math_functions(output);
    strings::emit_string_manipulation(output);
    io::emit_utility_functions(output);
    file::emit_file_io_functions(output);
    error::emit_error_handling(output);
    keyboard::emit_keyboard_functions(output);
    memory::emit_memory_functions(output);
    timing::emit_timing_functions(output);
    arrays::emit_array_functions(output);
    audio::emit_audio_functions(output);
    graphics::emit_graphics_stubs(output);
    legacy::emit_legacy_functions(output);
    legacy::emit_gosub_stack(output);
}
