/*
 * OpenGL call wrappers for QB64Fresh (optional; built only with feature "opengl").
 *
 * Each wrapper checks sub_gl_called (set by runtime when invoking SUB _GL);
 * if not set, raises QB64 error 270 (GL command outside SUB _GL).
 *
 * sub_gl_called is provided by the Rust runtime (gl_ffi.rs).
 *
 * All call_gl* wrappers (335 from gl.h) are generated by scripts/gl_parse_header.py
 * into gl_wrappers_generated.inc. call_gluPerspective is hand-added (GLU, not in gl.h).
 */

#include <stdint.h>

#if defined(_WIN32) || defined(WIN32)
#include <windows.h>
#endif
#include <GL/gl.h>
#include <GL/glu.h>

extern int sub_gl_called;
extern void qb_set_error(uint32_t code, int32_t line);

#define GL_CHECK() do { if (!sub_gl_called) { qb_set_error(270, 0); return; } } while (0)
#define GL_CHECK_RET(r) do { if (!sub_gl_called) { qb_set_error(270, 0); return (r); } } while (0)

#include "gl_wrappers_generated.inc"

void call_gluPerspective(double a, double b, double c, double d) {
    GL_CHECK();
    gluPerspective((GLdouble)a, (GLdouble)b, (GLdouble)c, (GLdouble)d);
}
