// Generated by scripts/gl_parse_header.py. Do not edit.

use super::SemanticAnalyzer;
use super::types::BasicType;

pub(super) fn register_gl_functions(s: &mut SemanticAnalyzer) {
    s.register_builtin_sub(
        "_GLACCUM",
        &[("p1", BasicType::Long), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub(
        "_GLALPHAFUNC",
        &[("p1", BasicType::Long), ("p2", BasicType::Single)],
    );
    s.register_builtin_function(
        "_GLARETEXTURESRESIDENT",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Offset),
            ("p3", BasicType::Offset),
        ],
        BasicType::Long,
    );
    s.register_builtin_sub("_GLARRAYELEMENT", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLBEGIN", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLBINDTEXTURE",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLBITMAP",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
            ("p5", BasicType::Single),
            ("p6", BasicType::Single),
            ("p7", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLBLENDFUNC",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLCALLLIST", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLCALLLISTS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub("_GLCLEAR", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLCLEARACCUM",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLCLEARCOLOR",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLCLEARDEPTH", &[("p1", BasicType::Double)]);
    s.register_builtin_sub("_GLCLEARINDEX", &[("p1", BasicType::Single)]);
    s.register_builtin_sub("_GLCLEARSTENCIL", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLCLIPPLANE",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLCOLOR3B",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3BV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3UB",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3UBV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3UI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3UIV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR3US",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR3USV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4B",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4BV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4UB",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4UBV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4UI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4UIV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLOR4US",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCOLOR4USV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLCOLORMASK",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLCOLORMATERIAL",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLCOLORPOINTER",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLCOPYPIXELS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLCOPYTEXIMAGE1D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLCOPYTEXIMAGE2D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Long),
            ("p8", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLCOPYTEXSUBIMAGE1D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLCOPYTEXSUBIMAGE2D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Long),
            ("p8", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLCULLFACE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLDELETELISTS",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLDELETETEXTURES",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub("_GLDEPTHFUNC", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLDEPTHMASK", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLDEPTHRANGE",
        &[("p1", BasicType::Double), ("p2", BasicType::Double)],
    );
    s.register_builtin_sub("_GLDISABLE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLDISABLECLIENTSTATE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLDRAWARRAYS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLDRAWBUFFER", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLDRAWELEMENTS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLDRAWPIXELS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Offset),
        ],
    );
    s.register_builtin_sub("_GLEDGEFLAG", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLEDGEFLAGPOINTER",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub("_GLEDGEFLAGV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLENABLE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLENABLECLIENTSTATE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLEND", &[]);
    s.register_builtin_sub("_GLENDLIST", &[]);
    s.register_builtin_sub("_GLEVALCOORD1D", &[("p1", BasicType::Double)]);
    s.register_builtin_sub("_GLEVALCOORD1DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLEVALCOORD1F", &[("p1", BasicType::Single)]);
    s.register_builtin_sub("_GLEVALCOORD1FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLEVALCOORD2D",
        &[("p1", BasicType::Double), ("p2", BasicType::Double)],
    );
    s.register_builtin_sub("_GLEVALCOORD2DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLEVALCOORD2F",
        &[("p1", BasicType::Single), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub("_GLEVALCOORD2FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLEVALMESH1",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLEVALMESH2",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLEVALPOINT1", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLEVALPOINT2",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLFEEDBACKBUFFER",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub("_GLFINISH", &[]);
    s.register_builtin_sub("_GLFLUSH", &[]);
    s.register_builtin_sub(
        "_GLFOGF",
        &[("p1", BasicType::Long), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub(
        "_GLFOGFV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLFOGI",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLFOGIV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub("_GLFRONTFACE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLFRUSTUM",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
            ("p5", BasicType::Double),
            ("p6", BasicType::Double),
        ],
    );
    s.register_builtin_function("_GLGENLISTS", &[("p1", BasicType::Long)], BasicType::Long);
    s.register_builtin_sub(
        "_GLGENTEXTURES",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETBOOLEANV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETCLIPPLANE",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETDOUBLEV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_function("_GLGETERROR", &[], BasicType::Long);
    s.register_builtin_sub(
        "_GLGETFLOATV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETINTEGERV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETLIGHTFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETLIGHTIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETMAPDV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETMAPFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETMAPIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETMATERIALFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETMATERIALIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETPIXELMAPFV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETPIXELMAPUIV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETPIXELMAPUSV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLGETPOINTERV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub("_GLGETPOLYGONSTIPPLE", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLGETTEXENVFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXENVIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXGENDV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXGENFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXGENIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXIMAGE",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXLEVELPARAMETERFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXLEVELPARAMETERIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXPARAMETERFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLGETTEXPARAMETERIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLHINT",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLINDEXMASK", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLINDEXPOINTER",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub("_GLINDEXD", &[("p1", BasicType::Double)]);
    s.register_builtin_sub("_GLINDEXDV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLINDEXF", &[("p1", BasicType::Single)]);
    s.register_builtin_sub("_GLINDEXFV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLINDEXI", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLINDEXIV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLINDEXS", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLINDEXSV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLINDEXUB", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLINDEXUBV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLINITNAMES", &[]);
    s.register_builtin_sub(
        "_GLINTERLEAVEDARRAYS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_function("_GLISENABLED", &[("p1", BasicType::Long)], BasicType::Long);
    s.register_builtin_function("_GLISLIST", &[("p1", BasicType::Long)], BasicType::Long);
    s.register_builtin_function("_GLISTEXTURE", &[("p1", BasicType::Long)], BasicType::Long);
    s.register_builtin_sub(
        "_GLLIGHTMODELF",
        &[("p1", BasicType::Long), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub(
        "_GLLIGHTMODELFV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLLIGHTMODELI",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLLIGHTMODELIV",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLLIGHTF",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLLIGHTFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLLIGHTI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLLIGHTIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLLINESTIPPLE",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLLINEWIDTH", &[("p1", BasicType::Single)]);
    s.register_builtin_sub("_GLLISTBASE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLLOADIDENTITY", &[]);
    s.register_builtin_sub("_GLLOADMATRIXD", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLLOADMATRIXF", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLLOADNAME", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLLOGICOP", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLMAP1D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLMAP1F",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLMAP2D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Double),
            ("p7", BasicType::Double),
            ("p8", BasicType::Long),
            ("p9", BasicType::Long),
            ("p10", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLMAP2F",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Single),
            ("p7", BasicType::Single),
            ("p8", BasicType::Long),
            ("p9", BasicType::Long),
            ("p10", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLMAPGRID1D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLMAPGRID1F",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLMAPGRID2D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Long),
            ("p5", BasicType::Double),
            ("p6", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLMAPGRID2F",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Long),
            ("p5", BasicType::Single),
            ("p6", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLMATERIALF",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLMATERIALFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLMATERIALI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLMATERIALIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub("_GLMATRIXMODE", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLMULTMATRIXD", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLMULTMATRIXF", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLNEWLIST",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLNORMAL3B",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLNORMAL3BV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLNORMAL3D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLNORMAL3DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLNORMAL3F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLNORMAL3FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLNORMAL3I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLNORMAL3IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLNORMAL3S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLNORMAL3SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLNORMALPOINTER",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLORTHO",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
            ("p5", BasicType::Double),
            ("p6", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLPASSTHROUGH", &[("p1", BasicType::Single)]);
    s.register_builtin_sub(
        "_GLPIXELMAPFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLPIXELMAPUIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLPIXELMAPUSV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLPIXELSTOREF",
        &[("p1", BasicType::Long), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub(
        "_GLPIXELSTOREI",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLPIXELTRANSFERF",
        &[("p1", BasicType::Long), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub(
        "_GLPIXELTRANSFERI",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLPIXELZOOM",
        &[("p1", BasicType::Single), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub("_GLPOINTSIZE", &[("p1", BasicType::Single)]);
    s.register_builtin_sub(
        "_GLPOLYGONMODE",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub(
        "_GLPOLYGONOFFSET",
        &[("p1", BasicType::Single), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub("_GLPOLYGONSTIPPLE", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLPOPATTRIB", &[]);
    s.register_builtin_sub("_GLPOPCLIENTATTRIB", &[]);
    s.register_builtin_sub("_GLPOPMATRIX", &[]);
    s.register_builtin_sub("_GLPOPNAME", &[]);
    s.register_builtin_sub(
        "_GLPRIORITIZETEXTURES",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Offset),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub("_GLPUSHATTRIB", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLPUSHCLIENTATTRIB", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLPUSHMATRIX", &[]);
    s.register_builtin_sub("_GLPUSHNAME", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLRASTERPOS2D",
        &[("p1", BasicType::Double), ("p2", BasicType::Double)],
    );
    s.register_builtin_sub("_GLRASTERPOS2DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS2F",
        &[("p1", BasicType::Single), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub("_GLRASTERPOS2FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS2I",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLRASTERPOS2IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS2S",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLRASTERPOS2SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS3D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS3DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS3F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS3FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS3I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS3IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS3S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS3SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS4D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS4DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS4F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS4FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS4I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS4IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLRASTERPOS4S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLRASTERPOS4SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLREADBUFFER", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLREADPIXELS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLRECTD",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLRECTDV",
        &[("p1", BasicType::Offset), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLRECTF",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLRECTFV",
        &[("p1", BasicType::Offset), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLRECTI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLRECTIV",
        &[("p1", BasicType::Offset), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub(
        "_GLRECTS",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLRECTSV",
        &[("p1", BasicType::Offset), ("p2", BasicType::Offset)],
    );
    s.register_builtin_function("_GLRENDERMODE", &[("p1", BasicType::Long)], BasicType::Long);
    s.register_builtin_sub(
        "_GLROTATED",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLROTATEF",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLSCALED",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLSCALEF",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLSCISSOR",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLSELECTBUFFER",
        &[("p1", BasicType::Long), ("p2", BasicType::Offset)],
    );
    s.register_builtin_sub("_GLSHADEMODEL", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLSTENCILFUNC",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLSTENCILMASK", &[("p1", BasicType::Long)]);
    s.register_builtin_sub(
        "_GLSTENCILOP",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD1D", &[("p1", BasicType::Double)]);
    s.register_builtin_sub("_GLTEXCOORD1DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLTEXCOORD1F", &[("p1", BasicType::Single)]);
    s.register_builtin_sub("_GLTEXCOORD1FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLTEXCOORD1I", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLTEXCOORD1IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub("_GLTEXCOORD1S", &[("p1", BasicType::Long)]);
    s.register_builtin_sub("_GLTEXCOORD1SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD2D",
        &[("p1", BasicType::Double), ("p2", BasicType::Double)],
    );
    s.register_builtin_sub("_GLTEXCOORD2DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD2F",
        &[("p1", BasicType::Single), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub("_GLTEXCOORD2FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD2I",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLTEXCOORD2IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD2S",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLTEXCOORD2SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD3D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD3DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD3F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD3FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD3I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD3IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD3S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD3SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD4D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD4DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD4F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD4FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD4I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD4IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORD4S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLTEXCOORD4SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLTEXCOORDPOINTER",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXENVF",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXENVFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXENVI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXENVIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXGEND",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXGENDV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXGENF",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXGENFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXGENI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXGENIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXIMAGE1D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Long),
            ("p8", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXIMAGE2D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Long),
            ("p8", BasicType::Long),
            ("p9", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXPARAMETERF",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXPARAMETERFV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXPARAMETERI",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXPARAMETERIV",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXSUBIMAGE1D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTEXSUBIMAGE2D",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
            ("p5", BasicType::Long),
            ("p6", BasicType::Long),
            ("p7", BasicType::Long),
            ("p8", BasicType::Long),
            ("p9", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLTRANSLATED",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub(
        "_GLTRANSLATEF",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub(
        "_GLVERTEX2D",
        &[("p1", BasicType::Double), ("p2", BasicType::Double)],
    );
    s.register_builtin_sub("_GLVERTEX2DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX2F",
        &[("p1", BasicType::Single), ("p2", BasicType::Single)],
    );
    s.register_builtin_sub("_GLVERTEX2FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX2I",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLVERTEX2IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX2S",
        &[("p1", BasicType::Long), ("p2", BasicType::Long)],
    );
    s.register_builtin_sub("_GLVERTEX2SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX3D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLVERTEX3DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX3F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLVERTEX3FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX3I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLVERTEX3IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX3S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLVERTEX3SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX4D",
        &[
            ("p1", BasicType::Double),
            ("p2", BasicType::Double),
            ("p3", BasicType::Double),
            ("p4", BasicType::Double),
        ],
    );
    s.register_builtin_sub("_GLVERTEX4DV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX4F",
        &[
            ("p1", BasicType::Single),
            ("p2", BasicType::Single),
            ("p3", BasicType::Single),
            ("p4", BasicType::Single),
        ],
    );
    s.register_builtin_sub("_GLVERTEX4FV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX4I",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLVERTEX4IV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEX4S",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
    s.register_builtin_sub("_GLVERTEX4SV", &[("p1", BasicType::Offset)]);
    s.register_builtin_sub(
        "_GLVERTEXPOINTER",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Offset),
        ],
    );
    s.register_builtin_sub(
        "_GLVIEWPORT",
        &[
            ("p1", BasicType::Long),
            ("p2", BasicType::Long),
            ("p3", BasicType::Long),
            ("p4", BasicType::Long),
        ],
    );
}
