/* Generated by QB64Fresh */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

#include "qb64fresh_rt.h"

typedef QbString qb_string;

/* Using external QB64Fresh runtime library */
/* Compile with: gcc -I<include_path> program.c -L<lib_path> -lqb64fresh_rt */

/* Global Variables */
int32_t x = 0;
double y = 0.0;
double result = 0.0;

int main(int argc, char** argv) {
    (void)argc; (void)argv;

    /* ' Simple test program for code generation */
    qb_print_string(qb_string_new("Hello, World!"));
    qb_print_newline();
    int32_t x = 0;
    x = 42LL;
    qb_print_string(qb_string_new("x = "));
    qb_print_int(x);
    qb_print_newline();
    double y = 0.0;
    y = 3.14000000000000012;
    qb_print_string(qb_string_new("y = "));
    qb_print_float(y);
    qb_print_newline();
    /* ' Simple loop */
    for (int32_t i = 1LL; (1 > 0) ? (i <= 3LL) : (i >= 3LL); i += 1) {
        qb_print_string(qb_string_new("Count: "));
        qb_print_int(i);
        qb_print_newline();
    }
    _qb_for_end_0:;
    /* ' Math */
    double result = 0.0;
    result = (double)((((10LL + 5LL)) * 2LL));
    qb_print_string(qb_string_new("Result = "));
    qb_print_float(result);
    qb_print_newline();
    if ((x > 10LL)) {
        qb_print_string(qb_string_new("x is greater than 10"));
        qb_print_newline();
    } else {
        qb_print_string(qb_string_new("x is not greater than 10"));
        qb_print_newline();
    }
    exit(0);

    return 0;
}
