/* Generated by QB64Fresh */
#ifndef _WIN32
#define _POSIX_C_SOURCE 199309L
#define _DEFAULT_SOURCE
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include <time.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <sys/time.h>
#ifdef __GLIBC__
#include <malloc.h>  /* For malloc_trim */
#endif
#endif

/* QB64 built-in constants */
#define _TRUE (-1)
#define _FALSE (0)
#define _EQUAL (0)
#define _GREATER (1)
#define _LESS (-1)
#define _STR_EMPTY (&_qbs_empty)
#define _STR_CRLF qb_string_new("\r\n")
#define _STR_LF qb_string_new("\n")
#define _STR_CR qb_string_new("\r")
#define _CHR_QUOTE qb_string_new("\"")
#define _CHR_HT qb_string_new("\t")
#define _CHR_LF qb_string_new("\n")

/* Keyboard constants */
#define _KEY_ESC (27)
#define _KEY_BACKSPACE (8)
#define _KEY_TAB (9)
#define _KEY_ENTER (13)
#define _KEY_UP (18432)
#define _KEY_DOWN (20480)
#define _KEY_LEFT (19200)
#define _KEY_RIGHT (19712)
#define _KEY_INSERT (20992)
#define _KEY_DELETE (21248)
#define _KEY_HOME (18176)
#define _KEY_END (20224)
#define _KEY_PAGEUP (18688)
#define _KEY_PAGEDOWN (20736)
#define _KEY_F1 (15104)
#define _KEY_F2 (15360)
#define _KEY_F3 (15616)
#define _KEY_F4 (15872)
#define _KEY_F5 (16128)
#define _KEY_F6 (16384)
#define _KEY_F7 (16640)
#define _KEY_F8 (16896)
#define _KEY_F9 (17152)
#define _KEY_F10 (17408)
#define _KEY_F11 (34048)
#define _KEY_F12 (34304)
#define _KEY_LSHIFT (100304)
#define _KEY_RSHIFT (100303)
#define _KEY_LCTRL (100306)
#define _KEY_RCTRL (100305)
#define _KEY_LALT (100308)
#define _KEY_RALT (100307)
#define _KEY_LAPPLE (100310)
#define _KEY_RAPPLE (100309)

/* Console constants */
#define _CONSOLE (-1)

/* ASCII constants */
#define _ASC_NUL (0)
#define _ASC_SOH (1)
#define _ASC_STX (2)
#define _ASC_ETX (3)
#define _ASC_EOT (4)
#define _ASC_ENQ (5)
#define _ASC_ACK (6)
#define _ASC_BEL (7)
#define _ASC_BS (8)
#define _ASC_HT (9)
#define _ASC_LF (10)
#define _ASC_VT (11)
#define _ASC_FF (12)
#define _ASC_CR (13)
#define _ASC_SO (14)
#define _ASC_SI (15)
#define _ASC_DLE (16)
#define _ASC_DC1 (17)
#define _ASC_DC2 (18)
#define _ASC_DC3 (19)
#define _ASC_DC4 (20)
#define _ASC_NAK (21)
#define _ASC_SYN (22)
#define _ASC_ETB (23)
#define _ASC_CAN (24)
#define _ASC_EM (25)
#define _ASC_SUB (26)
#define _ASC_ESC (27)
#define _ASC_FS (28)
#define _ASC_GS (29)
#define _ASC_RS (30)
#define _ASC_US (31)
#define _ASC_SPACE (32)
#define _ASC_EXCLAMATION (33)
#define _ASC_QUOTE (34)
#define _ASC_HASH (35)
#define _ASC_DOLLAR (36)
#define _ASC_PERCENT (37)
#define _ASC_AMPERSAND (38)
#define _ASC_APOSTROPHE (39)
#define _ASC_LEFTBRACKET (40)
#define _ASC_RIGHTBRACKET (41)
#define _ASC_ASTERISK (42)
#define _ASC_PLUS (43)
#define _ASC_COMMA (44)
#define _ASC_MINUS (45)
#define _ASC_FULLSTOP (46)
#define _ASC_FORWARDSLASH (47)
#define _ASC_COLON (58)
#define _ASC_SEMICOLON (59)
#define _ASC_LESSTHAN (60)
#define _ASC_EQUAL (61)
#define _ASC_GREATERTHAN (62)
#define _ASC_QUESTION (63)
#define _ASC_ATSIGN (64)
#define _ASC_LEFTSQUAREBRACKET (91)
#define _ASC_BACKSLASH (92)
#define _ASC_RIGHTSQUAREBRACKET (93)
#define _ASC_CARET (94)
#define _ASC_UNDERSCORE (95)
#define _ASC_GRAVE (96)
#define _ASC_LEFTCURLYBRACKET (123)
#define _ASC_VERTICALBAR (124)
#define _ASC_RIGHTCURLYBRACKET (125)
#define _ASC_TILDE (126)
#define _ASC_DEL (127)

/* Character string constants */
#define _CHR_NUL qb_string_new("\0")
#define _CHR_SOH qb_string_new("\x01")
#define _CHR_STX qb_string_new("\x02")
#define _CHR_ETX qb_string_new("\x03")
#define _CHR_EOT qb_string_new("\x04")
#define _CHR_ENQ qb_string_new("\x05")
#define _CHR_ACK qb_string_new("\x06")
#define _CHR_BEL qb_string_new("\x07")
#define _CHR_BS qb_string_new("\x08")
#define _CHR_VT qb_string_new("\x0B")
#define _CHR_FF qb_string_new("\x0C")
#define _CHR_CR qb_string_new("\r")
#define _CHR_SO qb_string_new("\x0E")
#define _CHR_SI qb_string_new("\x0F")
#define _CHR_DLE qb_string_new("\x10")
#define _CHR_DC1 qb_string_new("\x11")
#define _CHR_DC2 qb_string_new("\x12")
#define _CHR_DC3 qb_string_new("\x13")
#define _CHR_DC4 qb_string_new("\x14")
#define _CHR_NAK qb_string_new("\x15")
#define _CHR_SYN qb_string_new("\x16")
#define _CHR_ETB qb_string_new("\x17")
#define _CHR_CAN qb_string_new("\x18")
#define _CHR_EM qb_string_new("\x19")
#define _CHR_SUB qb_string_new("\x1A")
#define _CHR_ESC qb_string_new("\x1B")
#define _CHR_FS qb_string_new("\x1C")
#define _CHR_GS qb_string_new("\x1D")
#define _CHR_RS qb_string_new("\x1E")
#define _CHR_US qb_string_new("\x1F")
#define _CHR_SPACE qb_string_new(" ")
#define _CHR_EXCLAMATION qb_string_new("!")
#define _CHR_HASH qb_string_new("#")
#define _CHR_DOLLAR qb_string_new("$")
#define _CHR_PERCENT qb_string_new("%")
#define _CHR_AMPERSAND qb_string_new("&")
#define _CHR_APOSTROPHE qb_string_new("'")
#define _CHR_LEFTBRACKET qb_string_new("(")
#define _CHR_RIGHTBRACKET qb_string_new(")")
#define _CHR_ASTERISK qb_string_new("*")
#define _CHR_PLUS qb_string_new("+")
#define _CHR_COMMA qb_string_new(",")
#define _CHR_MINUS qb_string_new("-")
#define _CHR_FULLSTOP qb_string_new(".")
#define _CHR_FORWARDSLASH qb_string_new("/")
#define _CHR_COLON qb_string_new(":")
#define _CHR_SEMICOLON qb_string_new(";")
#define _CHR_LESSTHAN qb_string_new("<")
#define _CHR_EQUAL qb_string_new("=")
#define _CHR_GREATERTHAN qb_string_new(">")
#define _CHR_QUESTION qb_string_new("?")
#define _CHR_ATSIGN qb_string_new("@")
#define _CHR_LEFTSQUAREBRACKET qb_string_new("[")
#define _CHR_BACKSLASH qb_string_new("\\")
#define _CHR_RIGHTSQUAREBRACKET qb_string_new("]")
#define _CHR_CARET qb_string_new("^")
#define _CHR_UNDERSCORE qb_string_new("_")
#define _CHR_GRAVE qb_string_new("`")
#define _CHR_LEFTCURLYBRACKET qb_string_new("{")
#define _CHR_VERTICALBAR qb_string_new("|")
#define _CHR_RIGHTCURLYBRACKET qb_string_new("}")
#define _CHR_TILDE qb_string_new("~")
#define _CHR_DEL qb_string_new("\x7F")

/* Graphics pseudo-variables (zero-arg functions) */
#define _FONT qb_font_get()

#include "qb64fresh_rt.h"

typedef QbString qb_string;

/* Using external QB64Fresh runtime library */
/* Compile with: gcc -I<include_path> program.c -L<lib_path> -lqb64fresh_rt */

/* Error Handling Variables (functions in runtime library) */

static int32_t _qb_err = 0;
static int32_t _qb_erl = 0;
static void* _qb_error_handler = NULL;
static int _qb_error_resume_next = 0;
static void* _qb_error_line = NULL;
static int32_t _INCLERRORLINE = 0;
static char* _qb_err_msg = NULL;

/* GOSUB Return Stack */
#define GOSUB_STACK_SIZE 256
static void* _gosub_stack[GOSUB_STACK_SIZE];
static int _gosub_sp = 0;

static uint32_t _qb_strig_event_id = 0;

/* Empty string constant for external runtime */
static qb_string* _qbs_empty = NULL;
static void _init_qbs_empty(void) {
    if (!_qbs_empty) _qbs_empty = qb_string_empty();
}

#undef _STR_EMPTY
#define _STR_EMPTY (_qbs_empty ? _qbs_empty : (_init_qbs_empty(), _qbs_empty))

/* Dummy variables for LEN() type sizing pattern */
int32_t dummy = 0;
int8_t dummy_int_int = 0;
int16_t dummy_int = 0;
int64_t dummy_lng_lng = 0;
float dummy_sng = 0.0f;
double dummy_dbl = 0.0;
long double dummy_dbl_dbl = 0.0L;
intptr_t dummy_int_lng = 0;


/* Helper functions for external runtime */

int32_t qb_len_str(qb_string* s) {
    return s ? (int32_t)qb_string_len(s) : 0;
}

uint64_t qbs_tmp_base_get(void) { return 0; }
void qbs_cleanup(uint64_t base, int dummy) { (void)base; (void)dummy; }

void qb_mid_assign(qb_string** target, int32_t start, int32_t length, qb_string* value) {
    if (!target || !*target || !value) return;
    qb_string* s = *target;
    size_t s_len = qb_string_len(s);
    if (start < 1 || (size_t)start > s_len) return;
    size_t idx = (size_t)(start - 1);
    size_t max_len = s_len - idx;
    size_t replace_len;
    if (length < 0) {
        size_t value_len = qb_string_len(value);
        replace_len = (value_len < max_len) ? value_len : max_len;
    } else {
        replace_len = ((size_t)length < max_len) ? (size_t)length : max_len;
        size_t value_len = qb_string_len(value);
        if (replace_len > value_len) replace_len = value_len;
    }
    // Build new string: left part + replacement + right part
    qb_string* left_part = (idx > 0) ? qb_left(s, (int32_t)idx) : qb_string_empty();
    qb_string* replace_part = (replace_len > 0) ? qb_left(value, (int32_t)replace_len) : qb_string_empty();
    size_t right_start = idx + replace_len;
    qb_string* right_part = (right_start < s_len) ? qb_right(s, (int32_t)(s_len - right_start + 1)) : qb_string_empty();
    qb_string* temp = qb_string_concat(left_part, replace_part);
    qb_string* new_str = qb_string_concat(temp, right_part);
    // Clean up temporary strings
    if (left_part) qb_string_release(left_part);
    if (replace_part) qb_string_release(replace_part);
    if (right_part) qb_string_release(right_part);
    if (temp) qb_string_release(temp);
    // Release old target and set new string
    qb_string_release(*target);
    *target = new_str;
}

int32_t qb_instr2(qb_string* s, qb_string* find) {
    return qb_instr(1, s, find);
}

int32_t qb_controlchr(int32_t code) {
    return (code >= 0 && code <= 31) || code == 127;
}

void qb_file_open_legacy(int32_t fnum, const char* mode_char, const char* fname) {
    if (!mode_char || !fname) return;
    // Convert legacy mode character to standard mode string
    const char* mode;
    switch (mode_char[0]) {
        case 'I': case 'i': mode = "r"; break;
        case 'O': case 'o': mode = "w"; break;
        case 'A': case 'a': mode = "a"; break;
        case 'R': case 'r': mode = "r+b"; break;
        case 'B': case 'b': mode = "r+b"; break;
        default: mode = "r"; break;
    }
    qb_file_open(fnum, fname, mode);
}

int32_t qb_ubound2(void* arr, int32_t dim) {
    (void)arr; (void)dim;
    return 0;
}

qb_string* qb_mki(int16_t n) {
    uint8_t bytes[2];
    bytes[0] = (uint8_t)(n & 0xFF);
    bytes[1] = (uint8_t)((n >> 8) & 0xFF);
    return qb_string_from_bytes(bytes, 2);
}

qb_string* qb_string_fill_str(int32_t n, qb_string* c) {
    if (!c || qb_string_len(c) == 0) return qb_string_empty();
    const char* data = qb_string_data(c);
    int32_t char_code = (unsigned char)data[0];
    return qb_string_fill(n, char_code);
}

qb_string* qb_string_fill_code(int32_t n, int32_t code) {
    return qb_string_fill(n, code);
}

qb_string* qb_mid2(qb_string* s, int32_t start) {
    return qb_mid(s, start, -1);
}

int32_t qb_asc2(qb_string* s, int32_t pos) {
    if (!s || pos < 1 || pos > (int32_t)qb_string_len(s)) return 0;
    const char* data = qb_string_data(s);
    return (unsigned char)data[pos - 1];
}

void qb_array_register(void* ptr, int32_t lower, int32_t upper) {
    (void)ptr; (void)lower; (void)upper;
    // Array metadata registration not yet implemented
}

int32_t qb_ubound(void* arr) {
    (void)arr;
    return 0;
}

int32_t qb_cvl(qb_string* s) {
    if (!s || qb_string_len(s) < 4) return 0;
    const char* data = qb_string_data(s);
    int32_t result;
    memcpy(&result, data, 4);
    return result;
}

/* Command line arguments */
static int _qb_argc = 0;
static char** _qb_argv = NULL;

qb_string* qb_command_n(int64_t n) {
    if (n < 0 || n >= _qb_argc || !_qb_argv) return qb_string_empty();
    return qb_string_new(_qb_argv[n]);
}

int64_t qb_commandcount(void) {
    return _qb_argc - 1;
}

qb_string* qb_fullpath(qb_string* path) {
    if (!path) return qb_string_empty();
    const char* path_str = qb_string_data(path);
    char* resolved = realpath(path_str, NULL);
    if (resolved) {
        qb_string* result = qb_string_new(resolved);
        free(resolved);
        return result;
    }
    return qb_string_retain(path);
}

qb_string* qb_str(double n) {
    char buf[64];
    snprintf(buf, sizeof(buf), " %g", n);
    return qb_string_new(buf);
}

void qb_asc_assign(qb_string** s, int32_t pos, int32_t ch) {
    if (!s || !*s || pos < 1 || pos > (int32_t)qb_string_len(*s)) return;
    qb_string* old = *s;
    size_t len = qb_string_len(old);
    // Build new string: left + char + right
    qb_string* left = (pos > 1) ? qb_left(old, pos - 1) : qb_string_empty();
    qb_string* char_str = qb_chr(ch);
    qb_string* right = (pos < (int32_t)len) ? qb_right(old, (int32_t)(len - pos + 1)) : qb_string_empty();
    qb_string* temp = qb_string_concat(left, char_str);
    qb_string* new_str = qb_string_concat(temp, right);
    // Clean up
    if (left) qb_string_release(left);
    if (char_str) qb_string_release(char_str);
    if (right) qb_string_release(right);
    if (temp) qb_string_release(temp);
    qb_string_release(old);
    *s = new_str;
}

int64_t qb_shl(int64_t value, int32_t shift) {
    return shift >= 0 ? (value << shift) : (value >> (-shift));
}

void qb_file_get_string(int32_t fnum, qb_string* s) {
    if (!s) return;
    size_t len = qb_string_len(s);
    if (len == 0) return;
    // For external runtime, we need to use qb_file_get with the string's data
    // Note: This assumes the string buffer is writable, which may not be true for opaque types
    // For now, this is a stub - proper implementation requires runtime library support
    (void)fnum; (void)s;
}

void qb_array_register_md(void* ptr, int32_t num_dims, int32_t* lowers, int32_t* uppers) {
    (void)ptr; (void)num_dims; (void)lowers; (void)uppers;
    // Multi-dimensional array metadata registration not yet implemented
}

qb_string* qb_environ(qb_string* name) {
    if (!name) return qb_string_empty();
    const char* name_str = qb_string_data(name);
    const char* val = getenv(name_str);
    return val ? qb_string_new(val) : qb_string_empty();
}

int16_t qb_cvi(qb_string* s) {
    if (!s || qb_string_len(s) < 2) return 0;
    const char* data = qb_string_data(s);
    int16_t result;
    memcpy(&result, data, 2);
    return result;
}

qb_string* qb_mkl(int32_t n) {
    uint8_t bytes[4];
    memcpy(bytes, &n, 4);
    return qb_string_from_bytes(bytes, 4);
}

qb_string* qb_readfile(qb_string* path) {
    if (!path) return qb_string_empty();
    const char* path_str = qb_string_data(path);
    FILE* f = fopen(path_str, "rb");
    if (!f) return qb_string_empty();
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(size + 1);
    if (!buf) { fclose(f); return qb_string_empty(); }
    fread(buf, 1, size, f);
    buf[size] = '\0';
    fclose(f);
    qb_string* result = qb_string_from_bytes((uint8_t*)buf, size);
    free(buf);
    return result;
}

void qb_writefile(qb_string* path, qb_string* content) {
    if (!path || !content) return;
    const char* path_str = qb_string_data(path);
    const char* content_data = qb_string_data(content);
    size_t content_len = qb_string_len(content);
    FILE* f = fopen(path_str, "wb");
    if (!f) return;
    fwrite(content_data, 1, content_len, f);
    fclose(f);
}

qb_string* qb_deflate(qb_string* data) {
    (void)data;
    return qb_string_empty();
}

int32_t qb_red32(uint32_t c) { return (c >> 16) & 0xFF; }
int32_t qb_green32(uint32_t c) { return (c >> 8) & 0xFF; }
int32_t qb_blue32(uint32_t c) { return c & 0xFF; }

uint64_t qb_val_uint64(qb_string* s) {
    if (!s) return 0;
    const char* data = qb_string_data(s);
    return strtoull(data, NULL, 10);
}

int64_t qb_val_int64(qb_string* s) {
    if (!s) return 0;
    const char* data = qb_string_data(s);
    return strtoll(data, NULL, 10);
}

void qb_error(int32_t code) {
    fprintf(stderr, "ERROR %d\n", code);
    exit(code);
}

int32_t qb_sgn(double n) {
    if (n > 0) return 1;
    if (n < 0) return -1;
    return 0;
}

/* Additional stub functions for QB64PE compatibility */
int32_t qb_icon(void) { return 0; }
int32_t qb_acceptfiledrop(void) { return 0; }
int32_t qb_alpha(uint32_t c, int32_t mode) { (void)mode; return (c >> 24) & 0xFF; }
int32_t qb_alpha32(uint32_t c) { return (c >> 24) & 0xFF; }
double qb_arccot(double n) { return atan(1.0 / n); }
double qb_arccsc(double n) { return asin(1.0 / n); }
double qb_arcsec(double n) { return acos(1.0 / n); }
int32_t qb_backgroundcolor(void) { return 0; }
int32_t qb_blue(uint32_t c, int32_t mode) { (void)mode; return c & 0xFF; }
double qb_clamp(double x, double min, double max) { if (x < min) return min; if (x > max) return max; return x; }
int32_t qb_console(int32_t mode) { (void)mode; return 1; }
double qb_cot(double n) { return 1.0 / tan(n); }
double qb_coth(double n) { return 1.0 / tanh(n); }
double qb_csc(double n) { return 1.0 / sin(n); }
double qb_csch(double n) { return 1.0 / sinh(n); }
int32_t qb_csrlin(void) { return 1; }
double qb_cvd(qb_string* s) { if (!s || qb_string_len(s) < 8) return 0.0; double result; memcpy(&result, qb_string_data(s), 8); return result; }
double qb_cvq(qb_string* s) { if (!s || qb_string_len(s) < 8) return 0.0; double result; memcpy(&result, qb_string_data(s), 8); return result; }
float qb_cvs(qb_string* s) { if (!s || qb_string_len(s) < 4) return 0.0f; float result; memcpy(&result, qb_string_data(s), 4); return result; }
int32_t qb_defaultcolor(void) { return 7; }
void qb_def_seg(int32_t seg) { (void)seg; }
qb_string* qb_droppedfile_str(int32_t index) { (void)index; return qb_string_empty(); }
int32_t qb_exit_state(void) { return 0; }
void qb_finishdrop(void) { }
void qb_gfx_resize(int32_t flag) { (void)flag; }
int32_t qb_green(uint32_t c, int32_t mode) { (void)mode; return (c >> 8) & 0xFF; }
int32_t qb_lbound(void* arr) { (void)arr; return 0; }
int32_t qb_loadfont3(qb_string* path, int32_t size, qb_string* req) { (void)path; (void)size; (void)req; return 0; }
int32_t logical_drives(void) { return 0; }

/* Frame rate limiter for _LIMIT statement (external runtime) */
#ifndef _WIN32
#include <unistd.h>  /* For usleep */
#include <sys/time.h>  /* For gettimeofday */
#endif
static double qb_last_frame_time = 0.0;

#ifdef _WIN32
static double qb_get_time_seconds(void) {
    LARGE_INTEGER freq, count;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&count);
    return (double)count.QuadPart / (double)freq.QuadPart;
}
#else
static double qb_get_time_seconds(void) {
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return (double)tv.tv_sec + (double)tv.tv_usec / 1000000.0;
}
#endif

void qb_limit(int fps) {
    if (fps <= 0) return;
    double target_frame_time = 1.0 / (double)fps;
    double current_time = qb_get_time_seconds();
    if (qb_last_frame_time > 0.0) {
        double elapsed = current_time - qb_last_frame_time;
        double wait_time = target_frame_time - elapsed;
        if (wait_time > 0.0) {
#ifdef _WIN32
            Sleep((DWORD)(wait_time * 1000.0));
#else
            usleep((unsigned int)(wait_time * 1000000.0));
#endif
        }
    }
    qb_last_frame_time = qb_get_time_seconds();
}

/* Additional QB64PE-specific functions */
double qb_sec(double n) { return 1.0 / cos(n); }
double qb_sech(double n) { return 1.0 / cosh(n); }
int32_t qb_negate(int32_t n) { return -n; }
int32_t qb_red(uint32_t c, int32_t mode) { (void)mode; return (c >> 16) & 0xFF; }
uint32_t qb__rgb(int32_t r, int32_t g, int32_t b, int32_t mode) { (void)r; (void)g; (void)b; (void)mode; return 0; }
uint32_t qb__rgba(int32_t r, int32_t g, int32_t b, int32_t a, int32_t mode) { (void)r; (void)g; (void)b; (void)a; (void)mode; return 0; }
int32_t qb_messagebox4(qb_string* title, qb_string* message, int32_t type, int32_t icon) { (void)title; (void)message; (void)type; (void)icon; return 0; }
int64_t qb_timer_n(int32_t n) { (void)n; return 0; }
void qb_sub__font(int32_t handle) { (void)handle; }
void qb_sub__freefont(int32_t handle) { (void)handle; }
void qb_mapunicode(int32_t unicode_code, int32_t ascii_pos) { (void)unicode_code; (void)ascii_pos; }
int32_t qb__mapunicode1(int32_t code) { return code; }
int32_t qb_resize(void) { return 0; }
int32_t qb_resizewidth(void) { return 80; }
int32_t qb_resizeheight(void) { return 25; }
int32_t qb_pos(int64_t n) { (void)n; return 0; }
int32_t qb_screen(int32_t row, int32_t col) { (void)row; (void)col; return 32; }
int32_t qb_screen3(int32_t mode, int32_t depth, int32_t flags) { (void)mode; (void)depth; (void)flags; return 0; }
int32_t qb_screenx(void) { return 0; }
int32_t qb_screeny(void) { return 0; }
int32_t qb_readbit(qb_string* s, int32_t pos) { (void)s; (void)pos; return 0; }
qb_string* qb_openfiledialog5(qb_string* title, qb_string* filter, qb_string* def, qb_string* opts, int32_t flags) { (void)title; (void)filter; (void)def; (void)opts; (void)flags; return qb_string_empty(); }
qb_string* qb_savefiledialog4(qb_string* title, qb_string* filter, qb_string* def, int32_t flags) { (void)title; (void)filter; (void)def; (void)flags; return qb_string_empty(); }
int32_t qb_statuscode(int32_t handle) { (void)handle; return 0; }
int32_t qb_shellhide(qb_string* cmd) { (void)cmd; return 0; }
void qb_sub_set_foreground_window(intptr_t hwnd) { (void)hwnd; }
qb_string* qb_md5(qb_string* s) { (void)s; return qb_string_empty(); }
qb_string* qb_mkd(double n) { uint8_t bytes[8]; memcpy(bytes, &n, 8); return qb_string_from_bytes(bytes, 8); }
qb_string* qb_mkq(double n) { uint8_t bytes[8]; memcpy(bytes, &n, 8); return qb_string_from_bytes(bytes, 8); }
qb_string* qb_mks(float n) { uint8_t bytes[4]; memcpy(bytes, &n, 4); return qb_string_from_bytes(bytes, 4); }
int64_t qb_windowhasfocus(void) { return -1; }
void qb_view_print(int32_t top, int32_t bottom) { (void)top; (void)bottom; }
int32_t qb_totaldroppedfiles(void) { return 0; }

/* qb_sleep_keypress - SLEEP with no argument */
#ifdef _WIN32
#include <conio.h>
void qb_sleep_keypress(void) {
    _getch();
}
#else
#include <termios.h>
#include <unistd.h>
void qb_sleep_keypress(void) {
    struct termios oldt, newt;
    tcgetattr(STDIN_FILENO, &oldt);
    newt = oldt;
    newt.c_lflag &= ~(ICANON | ECHO);
    tcsetattr(STDIN_FILENO, TCSANOW, &newt);
    getchar();
    tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
}
#endif

/* User-Defined Types */
typedef struct qbt_HashListItem {
    int32_t Flags;
    int32_t Reference;
    int32_t NextItem;
    int32_t PrevItem;
    int32_t LastItem;
} qbt_HashListItem;

/* Global Variables */
qb_string* Version = NULL;
int8_t IsCiVersion = 0;
const int32_t Debug = 0LL;
char sp[2] = "";
char sp2[2] = "";
char sp3[2] = "";
int32_t sp_asc = 0;
int32_t sp2_asc = 0;
int32_t sp3_asc = 0;
char CHR_QUOTE[2] = "";
char CHR_TAB[2] = "";
qb_string* CRLF = NULL;
qb_string* NATIVE_LINEENDING = NULL;
int32_t OS_BITS = 0;
int32_t HashFind_NextListItem = 0;
int32_t HashFind_Reverse = 0;
int32_t HashFind_SearchFlags = 0;
qb_string* HashFind_Name = NULL;
int32_t HashRemove_LastFound = 0;
int32_t HashListSize = 0;
int32_t HashListNext = 0;
int32_t HashListFreeSize = 0;
int32_t HashListFreeLast = 0;
int16_t* hash1char = NULL;
size_t hash1char_sz__ = 0;
int16_t* hash2char = NULL;
size_t hash2char_sz__ = 0;
const int32_t HASHFLAG_LABEL = 2LL;
const int32_t HASHFLAG_TYPE = 4LL;
const int32_t HASHFLAG_RESERVED = 8LL;
const int32_t HASHFLAG_OPERATOR = 16LL;
const int32_t HASHFLAG_CUSTOMSYNTAX = 32LL;
const int32_t HASHFLAG_SUB = 64LL;
const int32_t HASHFLAG_FUNCTION = 128LL;
const int32_t HASHFLAG_UDT = 256LL;
const int32_t HASHFLAG_UDTELEMENT = 512LL;
const int32_t HASHFLAG_CONSTANT = 1024LL;
const int32_t HASHFLAG_VARIABLE = 2048LL;
const int32_t HASHFLAG_ARRAY = 4096LL;
const int32_t HASHFLAG_XELEMENTNAME = 8192LL;
const int32_t HASHFLAG_XTYPENAME = 16384LL;
int32_t constmax = 0;
int32_t constlast = 0;
int16_t test = 0;
qbt_HashListItem* HashList = NULL;
size_t HashList_sz__ = 0;
char (*HashListName)[257] = NULL;
size_t HashListName_sz__ = 0;
int32_t* HashListFree = NULL;
size_t HashListFree_sz__ = 0;
int32_t* HashTable = NULL;
size_t HashTable_sz__ = 0;
qb_string** constname = NULL;
size_t constname_sz__ = 0;
qb_string** constcname = NULL;
size_t constcname_sz__ = 0;
qb_string** constnamesymbol = NULL;
size_t constnamesymbol_sz__ = 0;
int32_t* consttype = NULL;
size_t consttype_sz__ = 0;
int64_t* constinteger = NULL;
size_t constinteger_sz__ = 0;
uint64_t* constuinteger = NULL;
size_t constuinteger_sz__ = 0;
long double* constfloat = NULL;
size_t constfloat_sz__ = 0;
qb_string** conststring = NULL;
size_t conststring_sz__ = 0;
int32_t* constsubfunc = NULL;
size_t constsubfunc_sz__ = 0;
int32_t* constdefined = NULL;
size_t constdefined_sz__ = 0;
int32_t versionfile = 0;
int32_t x = 0;
int32_t c1 = 0;
int32_t c2 = 0;

/* Forward Declarations */
int32_t qb_hashvalue_lng(qb_string** a_str_ref);
void qb_sub_hashadd(qb_string** a_str_ref, int32_t* flags_ref, int32_t* reference_ref);
int32_t qb_hashfind(qb_string** a_str_ref, int32_t* searchflags_ref, int32_t* resultflags_ref, int32_t* resultreference_ref);
int32_t qb_hashfindrev(qb_string** a_str_ref, int32_t* searchflags_ref, int32_t* resultflags_ref, int32_t* resultreference_ref);
int32_t qb_hashfindcont(int32_t* resultflags_ref, int32_t* resultreference_ref);
void qb_sub_hashremove(void);
void qb_sub_hashdump(void);
void qb_sub_hashclear(void);

int32_t qb_hashvalue_lng(qb_string** a_str_ref) {
    int32_t HashValue_lng = 0;
    qb_string* a_str = *a_str_ref;
    int32_t l = 0;
    int32_t a = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    l = qb_len_str(a_str);
    qbs_cleanup(_qbs_proc_base, 0);
    if (-(l == 0LL)) {
        *a_str_ref = a_str;
        return HashValue_lng;
    }
    qbs_cleanup(_qbs_proc_base, 0);
    a = qb_asc(a_str);
    qbs_cleanup(_qbs_proc_base, 0);
    if (-(a != 95LL)) {
        int32_t _qb_select_0 = l;
        if ((_qb_select_0 == 1LL)) {
            HashValue_lng = (hash1char[(int64_t)(a) - 0] + 1048576LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        } else if ((_qb_select_0 == 2LL)) {
            HashValue_lng = (hash2char[(int64_t)(qb_cvi(a_str)) - 0] + 2097152LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        } else if ((_qb_select_0 == 3LL)) {
            HashValue_lng = ((hash2char[(int64_t)(qb_cvi(a_str)) - 0] + (hash1char[(int64_t)(qb_asc2(a_str, 3LL)) - 0] * 1024LL)) + 3145728LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        } else {
            HashValue_lng = ((hash2char[(int64_t)(qb_cvi(a_str)) - 0] + (hash2char[(int64_t)((qb_asc2(a_str, l) + (qb_asc2(a_str, (l - 1LL)) * 256LL))) - 0] * 1024LL)) + (((l & 7LL)) * 1048576LL));
            *a_str_ref = a_str;
            return HashValue_lng;
        }
    } else {
        int32_t _qb_select_1 = l;
        if ((_qb_select_1 == 1LL)) {
            HashValue_lng = 9437184LL;
            *a_str_ref = a_str;
            return HashValue_lng;
        } else if ((_qb_select_1 == 2LL)) {
            HashValue_lng = (hash1char[(int64_t)(qb_asc2(a_str, 2LL)) - 0] + 10485760LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        } else if ((_qb_select_1 == 3LL)) {
            HashValue_lng = (hash2char[(int64_t)((qb_asc2(a_str, 2LL) + (qb_asc2(a_str, 3LL) * 256LL))) - 0] + 11534336LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        } else if ((_qb_select_1 == 4LL)) {
            HashValue_lng = ((hash2char[(int64_t)((((qb_cvl(a_str) & 16776960LL)) / 256LL)) - 0] + (hash1char[(int64_t)(qb_asc2(a_str, 4LL)) - 0] * 1024LL)) + 12582912LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        } else {
            HashValue_lng = (((hash2char[(int64_t)((((qb_cvl(a_str) & 16776960LL)) / 256LL)) - 0] + (hash2char[(int64_t)((qb_asc2(a_str, l) + (qb_asc2(a_str, (l - 1LL)) * 256LL))) - 0] * 1024LL)) + (((l & 7LL)) * 1048576LL)) + 8388608LL);
            *a_str_ref = a_str;
            return HashValue_lng;
        }
    }
    qbs_cleanup(_qbs_proc_base, 0);
    *a_str_ref = a_str;
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
    return HashValue_lng;
}

void qb_sub_hashadd(qb_string** a_str_ref, int32_t* flags_ref, int32_t* reference_ref) {
    qb_string* a_str = *a_str_ref;
    int32_t flags = *flags_ref;
    int32_t reference = *reference_ref;
    int32_t i = 0;
    int32_t x = 0;
    int32_t i2 = 0;
    int32_t i3 = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    if (-(HashListFreeLast > 0LL)) {
        i = HashListFree[(int64_t)(HashListFreeLast) - 0];
        HashListFreeLast = (HashListFreeLast - 1LL);
    } else {
        if (-(HashListNext > HashListSize)) {
            HashListSize = (HashListSize * 2LL);
            {
                size_t new_sz__ = sizeof(qbt_HashListItem) * ((HashListSize - 1LL + 1));
                HashList = realloc(HashList, new_sz__);
                if (new_sz__ > HashList_sz__) memset((char*)HashList + HashList_sz__, 0, new_sz__ - HashList_sz__);
                HashList_sz__ = new_sz__;
                qb_array_register(HashList, 1LL, HashListSize);
            }
            {
                size_t new_sz__ = sizeof(char[257]) * ((HashListSize - 1LL + 1));
                HashListName = realloc(HashListName, new_sz__);
                if (new_sz__ > HashListName_sz__) memset((char*)HashListName + HashListName_sz__, 0, new_sz__ - HashListName_sz__);
                HashListName_sz__ = new_sz__;
                qb_array_register(HashListName, 1LL, HashListSize);
            }
        }
        i = HashListNext;
        HashListNext = (HashListNext + 1LL);
    }
    qbs_cleanup(_qbs_proc_base, 0);
    x = qb_hashvalue_lng(&(a_str));
    qbs_cleanup(_qbs_proc_base, 0);
    i2 = HashTable[(int64_t)(x) - 0];
    qbs_cleanup(_qbs_proc_base, 0);
    if (i2) {
        i3 = HashList[(int64_t)(i2) - 0].LastItem;
        HashList[i2 - 0].LastItem = i;
        HashList[i3 - 0].NextItem = i;
        HashList[i - 0].PrevItem = i3;
    } else {
        HashTable[(int64_t)(x) - 0] = i;
        HashList[i - 0].PrevItem = 0LL;
        HashList[i - 0].LastItem = i;
    }
    qbs_cleanup(_qbs_proc_base, 0);
    HashList[i - 0].NextItem = 0LL;
    qbs_cleanup(_qbs_proc_base, 0);
    HashList[i - 0].Flags = flags;
    qbs_cleanup(_qbs_proc_base, 0);
    HashList[i - 0].Reference = reference;
    qbs_cleanup(_qbs_proc_base, 0);
    { qb_string* _tmp = qb_ucase(a_str); strncpy(HashListName[(int64_t)(i) - 0], _tmp ? qb_string_data(_tmp) : "", 256); HashListName[(int64_t)(i) - 0][256] = '\0'; }
    qbs_cleanup(_qbs_proc_base, 0);
    *a_str_ref = a_str;
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
}

int32_t qb_hashfind(qb_string** a_str_ref, int32_t* searchflags_ref, int32_t* resultflags_ref, int32_t* resultreference_ref) {
    int32_t HashFind = 0;
    qb_string* a_str = *a_str_ref;
    int32_t searchflags = *searchflags_ref;
    int32_t resultflags = *resultflags_ref;
    int32_t resultreference = *resultreference_ref;
    int32_t i = 0;
    qb_string* ua_str = NULL;
    int32_t f = 0;
    int32_t i2 = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    i = HashTable[(int64_t)(qb_hashvalue_lng(&(a_str))) - 0];
    qbs_cleanup(_qbs_proc_base, 0);
    if (i) {
        { qb_string* _new = qb_string_concat(qb_ucase(a_str), qb_space((256LL - qb_len_str(a_str)))); if (ua_str != _new) { qb_string_release(ua_str); ua_str = qb_string_retain(_new); } }
qb_hashfind_hashfind_next:
        f = HashList[(int64_t)(i) - 0].Flags;
        if ((searchflags & f)) {
            if (-(qb_string_compare(qb_str_from_c(HashListName[(int64_t)(i) - 0]), ua_str) == 0)) {
                resultflags = f;
                resultreference = HashList[(int64_t)(i) - 0].Reference;
                i2 = HashList[(int64_t)(i) - 0].NextItem;
                if (i2) {
                    HashFind = 2LL;
                    HashFind_NextListItem = i2;
                    HashFind_Reverse = 0LL;
                    HashFind_SearchFlags = searchflags;
                    { qb_string* _new = ua_str; if (HashFind_Name != _new) { qb_string_release(HashFind_Name); HashFind_Name = qb_string_retain(_new); } }
                    HashRemove_LastFound = i;
                    *a_str_ref = a_str;
                    return HashFind;
                } else {
                    HashFind = 1LL;
                    HashRemove_LastFound = i;
                    *a_str_ref = a_str;
                    return HashFind;
                }
            }
        }
        i = HashList[(int64_t)(i) - 0].NextItem;
        if (i) {
            goto qb_hashfind_hashfind_next;
        }
    }
    qbs_cleanup(_qbs_proc_base, 0);
    *a_str_ref = a_str;
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
    return HashFind;
}

int32_t qb_hashfindrev(qb_string** a_str_ref, int32_t* searchflags_ref, int32_t* resultflags_ref, int32_t* resultreference_ref) {
    int32_t HashFindRev = 0;
    qb_string* a_str = *a_str_ref;
    int32_t searchflags = *searchflags_ref;
    int32_t resultflags = *resultflags_ref;
    int32_t resultreference = *resultreference_ref;
    int32_t i = 0;
    qb_string* ua_str = NULL;
    int32_t f = 0;
    int32_t i2 = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    i = HashTable[(int64_t)(qb_hashvalue_lng(&(a_str))) - 0];
    qbs_cleanup(_qbs_proc_base, 0);
    if (i) {
        i = HashList[(int64_t)(i) - 0].LastItem;
        { qb_string* _new = qb_string_concat(qb_ucase(a_str), qb_space((256LL - qb_len_str(a_str)))); if (ua_str != _new) { qb_string_release(ua_str); ua_str = qb_string_retain(_new); } }
qb_hashfindrev_hashfindrev_next:
        f = HashList[(int64_t)(i) - 0].Flags;
        if ((searchflags & f)) {
            if (-(qb_string_compare(qb_str_from_c(HashListName[(int64_t)(i) - 0]), ua_str) == 0)) {
                resultflags = f;
                resultreference = HashList[(int64_t)(i) - 0].Reference;
                i2 = HashList[(int64_t)(i) - 0].PrevItem;
                if (i2) {
                    HashFindRev = 2LL;
                    HashFind_NextListItem = i2;
                    HashFind_Reverse = 1LL;
                    HashFind_SearchFlags = searchflags;
                    { qb_string* _new = ua_str; if (HashFind_Name != _new) { qb_string_release(HashFind_Name); HashFind_Name = qb_string_retain(_new); } }
                    HashRemove_LastFound = i;
                    *a_str_ref = a_str;
                    return HashFindRev;
                } else {
                    HashFindRev = 1LL;
                    HashRemove_LastFound = i;
                    *a_str_ref = a_str;
                    return HashFindRev;
                }
            }
        }
        i = HashList[(int64_t)(i) - 0].PrevItem;
        if (i) {
            goto qb_hashfindrev_hashfindrev_next;
        }
    }
    qbs_cleanup(_qbs_proc_base, 0);
    *a_str_ref = a_str;
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
    return HashFindRev;
}

int32_t qb_hashfindcont(int32_t* resultflags_ref, int32_t* resultreference_ref) {
    int32_t HashFindCont = 0;
    int32_t resultflags = *resultflags_ref;
    int32_t resultreference = *resultreference_ref;
    int32_t i = 0;
    int32_t f = 0;
    int32_t i2 = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    if (HashFind_Reverse) {
        i = HashFind_NextListItem;
qb_hashfindcont_hashfindrevc_next:
        f = HashList[(int64_t)(i) - 0].Flags;
        if ((HashFind_SearchFlags & f)) {
            if (-(qb_string_compare(qb_str_from_c(HashListName[(int64_t)(i) - 0]), HashFind_Name) == 0)) {
                resultflags = f;
                resultreference = HashList[(int64_t)(i) - 0].Reference;
                i2 = HashList[(int64_t)(i) - 0].PrevItem;
                if (i2) {
                    HashFindCont = 2LL;
                    HashFind_NextListItem = i2;
                    HashRemove_LastFound = i;
                    return HashFindCont;
                } else {
                    HashFindCont = 1LL;
                    HashRemove_LastFound = i;
                    return HashFindCont;
                }
            }
        }
        i = HashList[(int64_t)(i) - 0].PrevItem;
        if (i) {
            goto qb_hashfindcont_hashfindrevc_next;
        }
        return HashFindCont;
    } else {
        i = HashFind_NextListItem;
qb_hashfindcont_hashfindc_next:
        f = HashList[(int64_t)(i) - 0].Flags;
        if ((HashFind_SearchFlags & f)) {
            if (-(qb_string_compare(qb_str_from_c(HashListName[(int64_t)(i) - 0]), HashFind_Name) == 0)) {
                resultflags = f;
                resultreference = HashList[(int64_t)(i) - 0].Reference;
                i2 = HashList[(int64_t)(i) - 0].NextItem;
                if (i2) {
                    HashFindCont = 2LL;
                    HashFind_NextListItem = i2;
                    HashRemove_LastFound = i;
                    return HashFindCont;
                } else {
                    HashFindCont = 1LL;
                    HashRemove_LastFound = i;
                    return HashFindCont;
                }
            }
        }
        i = HashList[(int64_t)(i) - 0].NextItem;
        if (i) {
            goto qb_hashfindcont_hashfindc_next;
        }
        return HashFindCont;
    }
    qbs_cleanup(_qbs_proc_base, 0);
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
    return HashFindCont;
}

void qb_sub_hashremove(void) {
    int32_t i = 0;
    int32_t i1 = 0;
    int32_t i2 = 0;
    int32_t x = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    i = HashRemove_LastFound;
    qbs_cleanup(_qbs_proc_base, 0);
    HashListFreeLast = (HashListFreeLast + 1LL);
    qbs_cleanup(_qbs_proc_base, 0);
    if (-(HashListFreeLast > HashListFreeSize)) {
        HashListFreeSize = (HashListFreeSize * 2LL);
        {
            size_t new_sz__ = sizeof(int32_t) * ((HashListFreeSize - 1LL + 1));
            HashListFree = realloc(HashListFree, new_sz__);
            if (new_sz__ > HashListFree_sz__) memset((char*)HashListFree + HashListFree_sz__, 0, new_sz__ - HashListFree_sz__);
            HashListFree_sz__ = new_sz__;
            qb_array_register(HashListFree, 1LL, HashListFreeSize);
        }
    }
    qbs_cleanup(_qbs_proc_base, 0);
    HashListFree[(int64_t)(HashListFreeLast) - 0] = i;
    qbs_cleanup(_qbs_proc_base, 0);
    i1 = HashList[(int64_t)(i) - 0].PrevItem;
    qbs_cleanup(_qbs_proc_base, 0);
    if (i1) {
        i2 = HashList[(int64_t)(i) - 0].NextItem;
        if (i2) {
            HashList[i1 - 0].NextItem = i2;
            HashList[i2 - 0].LastItem = i1;
        } else {
            x = HashTable[(int64_t)(qb_hashvalue_lng(&(qb_string*){qb_str_from_c(ashListName[(int64_t)(i) - 0])})) - 0];
            HashList[x - 0].LastItem = i1;
            HashList[i1 - 0].NextItem = 0LL;
        }
    } else {
        x = HashTable[(int64_t)(qb_hashvalue_lng(&(qb_string*){qb_str_from_c(ashListName[(int64_t)(i) - 0])})) - 0];
        i2 = HashList[(int64_t)(i) - 0].NextItem;
        if (i2) {
            HashTable[(int64_t)(x) - 0] = i2;
            HashList[i2 - 0].PrevItem = 0LL;
            HashList[i2 - 0].LastItem = HashList[(int64_t)(i) - 0].LastItem;
        } else {
            HashTable[(int64_t)(x) - 0] = 0LL;
        }
    }
    qbs_cleanup(_qbs_proc_base, 0);
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
}

void qb_sub_hashdump(void) {
    int32_t fh = 0;
    qb_string* b_str = NULL;
    int32_t x = 0;
    int32_t i = 0;
    int32_t lasti = 0;
    qb_string* x_str = NULL;
    int32_t f = 0;
    int32_t z = 0;
    int32_t i1 = 0;
    int32_t i2 = 0;

    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    fh = ((int32_t)(qb_freefile()));
    qbs_cleanup(_qbs_proc_base, 0);
    qb_file_open_str(fh, qb_string_new("hashdump.txt"), "w");
    qbs_cleanup(_qbs_proc_base, 0);
    { qb_string* _new = qb_string_new("12345678901234567890123456789012}"); if (b_str != _new) { qb_string_release(b_str); b_str = qb_string_retain(_new); } }
    qbs_cleanup(_qbs_proc_base, 0);
    int32_t _qb_for_end_val_3 = 16777215LL;
    int64_t _qb_for_step_4 = 1;
    x = 0LL;
    uint64_t _qb_for_base_5 = qbs_tmp_base_get();
    for (; (_qb_for_step_4 > 0) ? (x <= _qb_for_end_val_3) : (x >= _qb_for_end_val_3); x += _qb_for_step_4) {
        /* STRIG event check */
        _qb_strig_event_id = qb_strig_check_event();
        if (_qb_strig_event_id) {
            _gosub_stack[_gosub_sp++] = &&_qb_strig_ret_6;
            goto _qb_strig_dispatch;
        }
        _qb_strig_ret_6:;
        qb_strig_event_done();
        qbs_cleanup(_qb_for_base_5, 0);
        if (HashTable[(int64_t)(x) - 0]) {
            qb_file_print_string(fh, qb_string_new("START HashTable("));
            qb_file_print_int(fh, x);
            qb_file_print_string(fh, qb_string_new("):"));
            qb_file_print_newline(fh);
            i = HashTable[(int64_t)(x) - 0];
            lasti = HashList[(int64_t)(i) - 0].LastItem;
            if (((-(HashList[(int64_t)(i) - 0].LastItem == 0LL) | -(HashList[(int64_t)(i) - 0].PrevItem != 0LL)) | -(qb_hashvalue_lng(&(qb_string*){qb_str_from_c(ashListName[(int64_t)(i) - 0])}) != x))) {
                goto qb_sub_hashdump_corrupt;
            }
            qb_file_print_string(fh, qb_string_new("  HashList("));
            qb_file_print_int(fh, i);
            qb_file_print_string(fh, qb_string_new(").LastItem="));
            qb_file_print_int(fh, HashList[(int64_t)(i) - 0].LastItem);
            qb_file_print_newline(fh);
qb_sub_hashdump_hashdumpnextitem:
            { qb_string* _new = qb_string_concat(qb_string_concat(qb_string_concat(qb_string_new("  ["), qb_tostr(i)), qb_string_new("]")), qb_str_from_c(HashListName[(int64_t)(i) - 0])); if (x_str != _new) { qb_string_release(x_str); x_str = qb_string_retain(_new); } }
            f = HashList[(int64_t)(i) - 0].Flags;
            { qb_string* _new = qb_string_concat(qb_string_concat(qb_string_concat(x_str, qb_string_new(",.Flags=")), qb_tostr(f)), qb_string_new("{")); if (x_str != _new) { qb_string_release(x_str); x_str = qb_string_retain(_new); } }
            int32_t _qb_for_end_val_8 = 32LL;
            int64_t _qb_for_step_9 = 1;
            z = 1LL;
            uint64_t _qb_for_base_10 = qbs_tmp_base_get();
            for (; (_qb_for_step_9 > 0) ? (z <= _qb_for_end_val_8) : (z >= _qb_for_end_val_8); z += _qb_for_step_9) {
                /* STRIG event check */
                _qb_strig_event_id = qb_strig_check_event();
                if (_qb_strig_event_id) {
                    _gosub_stack[_gosub_sp++] = &&_qb_strig_ret_11;
                    goto _qb_strig_dispatch;
                }
                _qb_strig_ret_11:;
                qb_strig_event_done();
                qbs_cleanup(_qb_for_base_10, 0);
                qb_asc_assign(&(b_str), z, (((f & 1LL)) + 48LL));
                f = (f / 2LL);
                qbs_cleanup(_qb_for_base_10, 0);
            }
            _qb_for_end_7:;
            { qb_string* _new = qb_string_concat(x_str, b_str); if (x_str != _new) { qb_string_release(x_str); x_str = qb_string_retain(_new); } }
            { qb_string* _new = qb_string_concat(qb_string_concat(x_str, qb_string_new(",.Reference=")), qb_tostr(HashList[(int64_t)(i) - 0].Reference)); if (x_str != _new) { qb_string_release(x_str); x_str = qb_string_retain(_new); } }
            qb_file_print_string(fh, x_str);
            qb_file_print_newline(fh);
            i1 = HashList[(int64_t)(i) - 0].PrevItem;
            i2 = HashList[(int64_t)(i) - 0].NextItem;
            if (i1) {
                if (-(HashList[(int64_t)(i1) - 0].NextItem != i)) {
                    goto qb_sub_hashdump_corrupt;
                }
            }
            if (i2) {
                if (-(HashList[(int64_t)(i2) - 0].PrevItem != i)) {
                    goto qb_sub_hashdump_corrupt;
                }
            }
            if (-(i2 == 0LL)) {
                if (-(lasti != i)) {
                    goto qb_sub_hashdump_corrupt;
                }
            }
            i = HashList[(int64_t)(i) - 0].NextItem;
            if (i) {
                goto qb_sub_hashdump_hashdumpnextitem;
            }
            qb_file_print_string(fh, qb_string_new("END HashTable("));
            qb_file_print_int(fh, x);
            qb_file_print_string(fh, qb_string_new(")"));
            qb_file_print_newline(fh);
        }
        qbs_cleanup(_qb_for_base_5, 0);
    }
    _qb_for_end_2:;
    qbs_cleanup(_qbs_proc_base, 0);
    qb_file_close(fh);
    qbs_cleanup(_qbs_proc_base, 0);
    return;
    qbs_cleanup(_qbs_proc_base, 0);
qb_sub_hashdump_corrupt:
    qbs_cleanup(_qbs_proc_base, 0);
    qb_file_print_string(fh, qb_string_new("HASH TABLE CORRUPT!"));
    qb_file_print_newline(fh);
    qbs_cleanup(_qbs_proc_base, 0);
    qb_file_close(fh);
    qbs_cleanup(_qbs_proc_base, 0);
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
}

void qb_sub_hashclear(void) {
    uint64_t _qbs_proc_base = qbs_tmp_base_get();

    HashListSize = 65536LL;
    qbs_cleanup(_qbs_proc_base, 0);
    HashListNext = 1LL;
    qbs_cleanup(_qbs_proc_base, 0);
    HashListFreeSize = 1024LL;
    qbs_cleanup(_qbs_proc_base, 0);
    HashListFreeLast = 0LL;
    qbs_cleanup(_qbs_proc_base, 0);
    {
        size_t new_sz__ = sizeof(qbt_HashListItem) * ((HashListSize - 1LL + 1));
        HashList = realloc(HashList, new_sz__);
        memset(HashList, 0, new_sz__);
        HashList_sz__ = new_sz__;
        qb_array_register(HashList, 1LL, HashListSize);
    }
    qbs_cleanup(_qbs_proc_base, 0);
    {
        size_t new_sz__ = sizeof(char[257]) * ((HashListSize - 1LL + 1));
        HashListName = realloc(HashListName, new_sz__);
        memset(HashListName, 0, new_sz__);
        HashListName_sz__ = new_sz__;
        qb_array_register(HashListName, 1LL, HashListSize);
    }
    qbs_cleanup(_qbs_proc_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((HashListFreeSize - 1LL + 1));
        HashListFree = realloc(HashListFree, new_sz__);
        memset(HashListFree, 0, new_sz__);
        HashListFree_sz__ = new_sz__;
        qb_array_register(HashListFree, 1LL, HashListFreeSize);
    }
    qbs_cleanup(_qbs_proc_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((16777215LL - 0 + 1));
        HashTable = realloc(HashTable, new_sz__);
        memset(HashTable, 0, new_sz__);
        HashTable_sz__ = new_sz__;
        qb_array_register(HashTable, 0, 16777215LL);
    }
    qbs_cleanup(_qbs_proc_base, 0);
    HashFind_NextListItem = 0LL;
    qbs_cleanup(_qbs_proc_base, 0);
    HashFind_Reverse = 0LL;
    qbs_cleanup(_qbs_proc_base, 0);
    HashFind_SearchFlags = 0LL;
    qbs_cleanup(_qbs_proc_base, 0);
    { qb_string* _new = qb_string_new(""); if (HashFind_Name != _new) { qb_string_release(HashFind_Name); HashFind_Name = qb_string_retain(_new); } }
    qbs_cleanup(_qbs_proc_base, 0);
    HashRemove_LastFound = 0LL;
    qbs_cleanup(_qbs_proc_base, 0);
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
_qb_strig_dispatch_end:
}

int main(int argc, char** argv) {
    /* Initialize runtime library */
    qb_runtime_init();
    /* Check for initialization errors */
    if (_qb_err != 0) {
        fprintf(stderr, "Error: Runtime initialization failed (error code %d)\n", _qb_err);
        if (_qb_erl > 0) {
            fprintf(stderr, "  At line %ld\n", (long)_qb_erl);
        }
        if (_qb_err_msg && strlen(_qb_err_msg) > 0) {
            fprintf(stderr, "  %s\n", _qb_err_msg);
        }
        fflush(stderr);
        return 1;
    }
    /* Initialize command-line arguments */
    qb_init_args(argc, argv);
    /* Initialize start directory */
    qb_init_startdir();
    if (_qb_err != 0) {
        fprintf(stderr, "Error: Failed to initialize start directory (error code %d)\n", _qb_err);
        fflush(stderr);
        return 1;
    }
    /* Initialize VGA palette */
    _qb_init_palette();
    static uint32_t _qb_strig_event_id = 0;

    /* Initialize string constants */
    Version = qb_string_new("");;
    CRLF = qb_string_new("");;
    NATIVE_LINEENDING = qb_string_new("");;
    HashFind_Name = qb_string_new("");;

    uint64_t _qbs_main_base = qbs_tmp_base_get();

    /* Implicit local variables */
    long double* constfloat = NULL;
    static size_t constfloat_sz__ = 0;
    qb_string* VersionLabel_str = NULL;

    qbs_cleanup(_qbs_main_base, 0);
    /* $CONSOLE - enable console window */
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _new = qb_string_new("4.3.0"); if (Version != _new) { qb_string_release(Version); Version = qb_string_retain(_new); } }
    qbs_cleanup(_qbs_main_base, 0);
    /* $VERSIONINFO:FILEVERSION#=4,3,0,0 */
    qbs_cleanup(_qbs_main_base, 0);
    /* $VERSIONINFO:PRODUCTVERSION#=4,3,0,0 */
    qbs_cleanup(_qbs_main_base, 0);
    if (qb_file_exists(qb_string_new("internal/version.txt"))) {
        versionfile = ((int32_t)(qb_freefile()));
        qb_file_open_str(versionfile, qb_string_new("internal/version.txt"), "r");
        qb_file_line_input(versionfile, &VersionLabel_str);
        { qb_string* _new = qb_string_concat(Version, VersionLabel_str); if (Version != _new) { qb_string_release(Version); Version = qb_string_retain(_new); } }
        if ((-(qb_string_compare(VersionLabel_str, qb_string_new("")) != 0) & -(qb_string_compare(VersionLabel_str, qb_string_new("-UNKNOWN")) != 0))) {
            IsCiVersion = ((int8_t)(_TRUE));
        }
        qb_file_close(versionfile);
    }
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t Debug = 0LL;
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _tmp = _CHR_CR; strncpy(sp, _tmp ? qb_string_data(_tmp) : "", 1); sp[1] = '\0'; }
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _tmp = _CHR_LF; strncpy(sp2, _tmp ? qb_string_data(_tmp) : "", 1); sp2[1] = '\0'; }
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _tmp = _CHR_SUB; strncpy(sp3, _tmp ? qb_string_data(_tmp) : "", 1); sp3[1] = '\0'; }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    sp_asc = ((int32_t)(_ASC_CR));
    qbs_cleanup(_qbs_main_base, 0);
    sp2_asc = ((int32_t)(_ASC_LF));
    qbs_cleanup(_qbs_main_base, 0);
    sp3_asc = ((int32_t)(_ASC_SUB));
    qbs_cleanup(_qbs_main_base, 0);
    if (Debug) {
        { qb_string* _tmp = qb_string_new("ú"); strncpy(sp, _tmp ? qb_string_data(_tmp) : "", 1); sp[1] = '\0'; }
        { qb_string* _tmp = qb_string_new("ù"); strncpy(sp2, _tmp ? qb_string_data(_tmp) : "", 1); sp2[1] = '\0'; }
        { qb_string* _tmp = qb_string_new("³"); strncpy(sp3, _tmp ? qb_string_data(_tmp) : "", 1); sp3[1] = '\0'; }
    }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _tmp = _CHR_QUOTE; strncpy(CHR_QUOTE, _tmp ? qb_string_data(_tmp) : "", 1); CHR_QUOTE[1] = '\0'; }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _tmp = _CHR_HT; strncpy(CHR_TAB, _tmp ? qb_string_data(_tmp) : "", 1); CHR_TAB[1] = '\0'; }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    { qb_string* _new = _STR_CRLF; if (CRLF != _new) { qb_string_release(CRLF); CRLF = qb_string_retain(_new); } }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    if (qb_instr2(qb_os(), qb_string_new("WIN"))) {
        { qb_string* _new = _STR_CRLF; if (NATIVE_LINEENDING != _new) { qb_string_release(NATIVE_LINEENDING); NATIVE_LINEENDING = qb_string_retain(_new); } }
    } else {
        { qb_string* _new = _STR_LF; if (NATIVE_LINEENDING != _new) { qb_string_release(NATIVE_LINEENDING); NATIVE_LINEENDING = qb_string_retain(_new); } }
    }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    OS_BITS = 64LL;
    qbs_cleanup(_qbs_main_base, 0);
    if (qb_instr2(qb_os(), qb_string_new("[32BIT]"))) {
        OS_BITS = 32LL;
    }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    hash1char = malloc(sizeof(int16_t) * (256));
    qb_array_register(hash1char, 0, 255);
    qbs_cleanup(_qbs_main_base, 0);
    hash2char = malloc(sizeof(int16_t) * (65536));
    qb_array_register(hash2char, 0, 65535);
    qbs_cleanup(_qbs_main_base, 0);
    int32_t _qb_for_end_val_13 = 26LL;
    int64_t _qb_for_step_14 = 1;
    x = 1LL;
    uint64_t _qb_for_base_15 = qbs_tmp_base_get();
    for (; (_qb_for_step_14 > 0) ? (x <= _qb_for_end_val_13) : (x >= _qb_for_end_val_13); x += _qb_for_step_14) {
        /* STRIG event check */
        _qb_strig_event_id = qb_strig_check_event();
        if (_qb_strig_event_id) {
            _gosub_stack[_gosub_sp++] = &&_qb_strig_ret_16;
            goto _qb_strig_dispatch;
        }
        _qb_strig_ret_16:;
        qb_strig_event_done();
        qbs_cleanup(_qb_for_base_15, 0);
        hash1char[(int64_t)((64LL + x)) - 0] = ((int16_t)(x));
        hash1char[(int64_t)((96LL + x)) - 0] = ((int16_t)(x));
        qbs_cleanup(_qb_for_base_15, 0);
    }
    _qb_for_end_12:;
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(95LL) - 0] = ((int16_t)(27LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(48LL) - 0] = ((int16_t)(28LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(49LL) - 0] = ((int16_t)(29LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(50LL) - 0] = ((int16_t)(30LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(51LL) - 0] = ((int16_t)(31LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(52LL) - 0] = ((int16_t)(23LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(53LL) - 0] = ((int16_t)(22LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(54LL) - 0] = ((int16_t)(20LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(55LL) - 0] = ((int16_t)(19LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(56LL) - 0] = ((int16_t)(18LL));
    qbs_cleanup(_qbs_main_base, 0);
    hash1char[(int64_t)(57LL) - 0] = ((int16_t)(17LL));
    qbs_cleanup(_qbs_main_base, 0);
    int32_t _qb_for_end_val_18 = 255LL;
    int64_t _qb_for_step_19 = 1;
    c1 = 0LL;
    uint64_t _qb_for_base_20 = qbs_tmp_base_get();
    for (; (_qb_for_step_19 > 0) ? (c1 <= _qb_for_end_val_18) : (c1 >= _qb_for_end_val_18); c1 += _qb_for_step_19) {
        /* STRIG event check */
        _qb_strig_event_id = qb_strig_check_event();
        if (_qb_strig_event_id) {
            _gosub_stack[_gosub_sp++] = &&_qb_strig_ret_21;
            goto _qb_strig_dispatch;
        }
        _qb_strig_ret_21:;
        qb_strig_event_done();
        qbs_cleanup(_qb_for_base_20, 0);
        int32_t _qb_for_end_val_23 = 255LL;
        int64_t _qb_for_step_24 = 1;
        c2 = 0LL;
        uint64_t _qb_for_base_25 = qbs_tmp_base_get();
        for (; (_qb_for_step_24 > 0) ? (c2 <= _qb_for_end_val_23) : (c2 >= _qb_for_end_val_23); c2 += _qb_for_step_24) {
            /* STRIG event check */
            _qb_strig_event_id = qb_strig_check_event();
            if (_qb_strig_event_id) {
                _gosub_stack[_gosub_sp++] = &&_qb_strig_ret_26;
                goto _qb_strig_dispatch;
            }
            _qb_strig_ret_26:;
            qb_strig_event_done();
            qbs_cleanup(_qb_for_base_25, 0);
            hash2char[(int64_t)((c1 + (c2 * 256LL))) - 0] = ((int16_t)((hash1char[(int64_t)(c1) - 0] + (hash1char[(int64_t)(c2) - 0] * 32LL))));
            qbs_cleanup(_qb_for_base_25, 0);
        }
        _qb_for_end_22:;
        qbs_cleanup(_qb_for_base_20, 0);
    }
    _qb_for_end_17:;
    qbs_cleanup(_qbs_main_base, 0);
    HashListSize = 65536LL;
    qbs_cleanup(_qbs_main_base, 0);
    HashListNext = 1LL;
    qbs_cleanup(_qbs_main_base, 0);
    HashListFreeSize = 1024LL;
    qbs_cleanup(_qbs_main_base, 0);
    HashListFreeLast = 0LL;
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(qbt_HashListItem) * ((HashListSize - 1LL + 1));
        HashList = realloc(HashList, new_sz__);
        memset(HashList, 0, new_sz__);
        HashList_sz__ = new_sz__;
        qb_array_register(HashList, 1LL, HashListSize);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(char[257]) * ((HashListSize - 1LL + 1));
        HashListName = realloc(HashListName, new_sz__);
        memset(HashListName, 0, new_sz__);
        HashListName_sz__ = new_sz__;
        qb_array_register(HashListName, 1LL, HashListSize);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((HashListFreeSize - 1LL + 1));
        HashListFree = realloc(HashListFree, new_sz__);
        memset(HashListFree, 0, new_sz__);
        HashListFree_sz__ = new_sz__;
        qb_array_register(HashListFree, 1LL, HashListFreeSize);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((16777215LL - 0 + 1));
        HashTable = realloc(HashTable, new_sz__);
        memset(HashTable, 0, new_sz__);
        HashTable_sz__ = new_sz__;
        qb_array_register(HashTable, 0, 16777215LL);
    }
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_LABEL = 2LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_TYPE = 4LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_RESERVED = 8LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_OPERATOR = 16LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_CUSTOMSYNTAX = 32LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_SUB = 64LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_FUNCTION = 128LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_UDT = 256LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_UDTELEMENT = 512LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_CONSTANT = 1024LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_VARIABLE = 2048LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_ARRAY = 4096LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_XELEMENTNAME = 8192LL;
    qbs_cleanup(_qbs_main_base, 0);
    const int32_t HASHFLAG_XTYPENAME = 16384LL;
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    constmax = 100LL;
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    constlast = -1LL;
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(qb_string*) * ((constmax - 0 + 1));
        constname = realloc(constname, new_sz__);
        memset(constname, 0, new_sz__);
        constname_sz__ = new_sz__;
        qb_array_register(constname, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(qb_string*) * ((constmax - 0 + 1));
        constcname = realloc(constcname, new_sz__);
        memset(constcname, 0, new_sz__);
        constcname_sz__ = new_sz__;
        qb_array_register(constcname, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(qb_string*) * ((constmax - 0 + 1));
        constnamesymbol = realloc(constnamesymbol, new_sz__);
        memset(constnamesymbol, 0, new_sz__);
        constnamesymbol_sz__ = new_sz__;
        qb_array_register(constnamesymbol, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((constmax - 0 + 1));
        consttype = realloc(consttype, new_sz__);
        memset(consttype, 0, new_sz__);
        consttype_sz__ = new_sz__;
        qb_array_register(consttype, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(int64_t) * ((constmax - 0 + 1));
        constinteger = realloc(constinteger, new_sz__);
        memset(constinteger, 0, new_sz__);
        constinteger_sz__ = new_sz__;
        qb_array_register(constinteger, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(uint64_t) * ((constmax - 0 + 1));
        constuinteger = realloc(constuinteger, new_sz__);
        memset(constuinteger, 0, new_sz__);
        constuinteger_sz__ = new_sz__;
        qb_array_register(constuinteger, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(long double) * ((constmax - 0 + 1));
        constfloat = realloc(constfloat, new_sz__);
        memset(constfloat, 0, new_sz__);
        constfloat_sz__ = new_sz__;
        qb_array_register(constfloat, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(qb_string*) * ((constmax - 0 + 1));
        conststring = realloc(conststring, new_sz__);
        memset(conststring, 0, new_sz__);
        conststring_sz__ = new_sz__;
        qb_array_register(conststring, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((constmax - 0 + 1));
        constsubfunc = realloc(constsubfunc, new_sz__);
        memset(constsubfunc, 0, new_sz__);
        constsubfunc_sz__ = new_sz__;
        qb_array_register(constsubfunc, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    {
        size_t new_sz__ = sizeof(int32_t) * ((constmax - 0 + 1));
        constdefined = realloc(constdefined, new_sz__);
        memset(constdefined, 0, new_sz__);
        constdefined_sz__ = new_sz__;
        qb_array_register(constdefined, 0, constmax);
    }
    qbs_cleanup(_qbs_main_base, 0);
    qbs_cleanup(_qbs_main_base, 0);
    test = ((int16_t)(1LL));
    qbs_cleanup(_qbs_main_base, 0);
    qb_print_string(qb_string_new("Hash table utility test"));
    qb_print_newline();
    qbs_cleanup(_qbs_main_base, 0);

    /* STRIG Event Dispatch */
    goto _qb_strig_dispatch_end;
_qb_strig_dispatch:
    goto *_gosub_stack[--_gosub_sp];
_qb_strig_dispatch_end:

    /* Shutdown runtime library */
    qb_runtime_shutdown();
    if (_qb_err != 0) {
        fprintf(stderr, "Warning: Runtime shutdown reported error (code %d)\n", _qb_err);
        fflush(stderr);
    }
    return 0;
}
