#!/usr/bin/env python3
"""
Parse QB64pe gl.h to generate:
- GL constant (name, value) pairs for Rust register_builtin_constant
- _GL* function (name, is_void, param_types) for Rust registration and C wrappers

Usage: python3 gl_parse_header.py <path-to-gl.h>
Output: prints Rust constant registration and function registration to stdout;
        C wrappers to stderr (or we split). For simplicity we print all to stdout
        with section markers.

Reference: docs/QB64pe/QB64PE_OPENGL_FUNCTIONALITY.md
"""

import re
import sys
from pathlib import Path


def parse_constants(content: str) -> list[tuple[str, int]]:
    """Extract #define GL_NAME value. Resolve simple aliases (GL_X GL_Y). Two passes."""
    constants: dict[str, int] = {}
    aliases: list[tuple[str, str]] = []
    for m in re.finditer(r"#define\s+(GL_[A-Za-z0-9_]+)\s+(.+)", content):
        name, value_str = m.group(1), m.group(2).strip()
        value_str = value_str.split("/*")[0].strip().rstrip()
        if re.match(r"0x[0-9a-fA-F]+$", value_str):
            constants[name] = int(value_str, 16)
        elif re.match(r"[0-9]+$", value_str):
            constants[name] = int(value_str, 10)
        elif re.match(r"GL_[A-Za-z0-9_]+$", value_str):
            aliases.append((name, value_str))
        # else skip
    for name, ref in aliases:
        if ref in constants:
            constants[name] = constants[ref]
    return sorted(constants.items())


def c_type_to_basic(s: str) -> str:
    """Map OpenGL C type to BasicType::X for Rust (Long, Single, Double, Offset)."""
    s = s.strip()
    if "*" in s:
        return "BasicType::Offset"
    if "double" in s.lower() or "GLclampd" in s:
        return "BasicType::Double"
    if "float" in s.lower() or "GLfloat" in s or "GLclampf" in s:
        return "BasicType::Single"
    return "BasicType::Long"  # GLenum, GLint, GLsizei, GLuint, GLboolean, etc.


def parse_param(p: str) -> tuple[str, str]:
    """Parse 'GLenum mode' or 'const GLvoid *lists' -> (c_type, name)."""
    p = p.strip()
    # Last token is param name
    parts = p.split()
    if not parts:
        return ("void", "unused")
    name = parts[-1].lstrip("*")
    c_type = p[: p.rfind(name)].strip().rstrip()
    if not c_type:
        c_type = "void"
    return (c_type, name)


def c_type_to_wrapper(c_type: str) -> str:
    """Map OpenGL C type to wrapper param type (uint32_t, int32_t, float, double, void*)."""
    if "*" in c_type:
        return "void *" if "const" not in c_type else "const void *"
    if "double" in c_type.lower() or "GLclampd" in c_type:
        return "double"
    if "float" in c_type.lower() or "GLfloat" in c_type or "GLclampf" in c_type:
        return "float"
    if "short" in c_type.lower() or "GLshort" in c_type or "GLushort" in c_type:
        return "int32_t"
    if "byte" in c_type.lower() or "GLbyte" in c_type or "GLubyte" in c_type:
        return "int32_t"
    return "uint32_t"  # GLenum, GLint, GLsizei, GLuint, GLboolean, GLbitfield


def parse_functions(
    content: str,
) -> list[tuple[str, str, bool, list[str], list[tuple[str, str]]]]:
    """Extract declarations; return (basic_name, gl_c_name, is_void, basic_param_types, c_params)."""
    pattern = re.compile(
        r"WINGDIAPI\s+(void|GL\w+)\s+APIENTRY\s+gl(\w+)\s*\((.*?)\)\s*;",
        re.DOTALL,
    )
    results = []
    for m in pattern.finditer(content):
        ret, basename, params_str = m.group(1), m.group(2), m.group(3)
        gl_c_name = "gl" + basename
        is_void = ret == "void"
        param_types: list[str] = []
        c_params: list[tuple[str, str]] = []
        params_str = params_str.strip()
        if params_str and params_str != "void":
            for p in params_str.split(","):
                p = p.strip()
                if p == "void":
                    continue
                param_types.append(c_type_to_basic(p))
                c_params.append(parse_param(p))
        results.append(
            (f"_GL{basename.upper()}", gl_c_name, is_void, param_types, c_params)
        )
    return results


def emit_rust_constants(constants: list[tuple[str, int]], out: list[str]) -> None:
    """Emit const GL_CONSTANTS array for include in builtins_opengl.rs."""
    out.append("/// Generated by scripts/gl_parse_header.py from QB64pe gl.h. Do not edit.")
    out.append("")
    out.append("const GL_CONSTANTS: &[(&str, i64)] = &[")
    for name, value in constants:
        out.append(f'    ("{name}", {value}),')
    out.append("];")
    out.append("")


def emit_rust_functions(
    functions: list[
        tuple[str, str, bool, list[str], list[tuple[str, str]]]
    ],
    out: list[str],
) -> None:
    """Emit a module with register_gl_functions(s) that registers all _GL* from gl.h."""
    out.append("// Generated by scripts/gl_parse_header.py. Do not edit.")
    out.append("")
    out.append("use super::SemanticAnalyzer;")
    out.append("use super::types::BasicType;")
    out.append("")
    out.append("pub(super) fn register_gl_functions(s: &mut SemanticAnalyzer) {")
    param_names = ["p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8", "p9", "p10", "p11", "p12"]
    for basic_name, _gl_c_name, is_void, param_types, _ in functions:
        n = len(param_types)
        params = ", ".join(
            f'("{param_names[i]}", {param_types[i]})' for i in range(n)
        )
        if is_void:
            out.append(f'    s.register_builtin_sub("{basic_name}", &[{params}]);')
        else:
            out.append(
                f'    s.register_builtin_function("{basic_name}", &[{params}], BasicType::Long);'
            )
    out.append("}")
    out.append("")


def emit_c_wrappers(
    functions: list[
        tuple[str, str, bool, list[str], list[tuple[str, str]]]
    ],
    out: list[str],
) -> None:
    """Emit C wrapper functions for gl_wrappers_generated.inc."""
    out.append("/* Generated by scripts/gl_parse_header.py. Do not edit. */")
    out.append("")
    for _basic_name, gl_name, is_void, _, c_params in functions:
        # Skip (void) param - C uses "void" for no-args, don't use as param name
        effective = [(t, n) for t, n in c_params if t and n != "void"]
        w_params = []
        cast_args = []
        for i, (c_type, name) in enumerate(effective):
            w_type = c_type_to_wrapper(c_type)
            pname = name if name != "unused" else f"p{i+1}"
            w_params.append(f"{w_type} {pname}")
            cast_args.append(f"({c_type}){pname}")
        params_str = ", ".join(w_params) if w_params else "void"
        args_str = ", ".join(cast_args)
        if is_void:
            out.append(
                f"void call_{gl_name}({params_str}) {{ GL_CHECK(); {gl_name}({args_str}); }}"
            )
        else:
            out.append(
                f"uint32_t call_{gl_name}({params_str}) {{ GL_CHECK_RET(0); return (uint32_t){gl_name}({args_str}); }}"
            )
    out.append("")


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: gl_parse_header.py <path-to-gl.h> [output-dir]", file=sys.stderr)
        sys.exit(1)
    path = Path(sys.argv[1])
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("src/semantic")
    content = path.read_text()

    constants = parse_constants(content)
    functions = parse_functions(content)

    # Write constants file (const array)
    const_lines: list[str] = []
    emit_rust_constants(constants, const_lines)
    (out_dir / "builtins_opengl_constants.rs").write_text("\n".join(const_lines))

    # Write function registration module (register_gl_functions(s))
    fn_lines: list[str] = []
    emit_rust_functions(functions, fn_lines)
    (out_dir / "builtins_opengl_functions.rs").write_text("\n".join(fn_lines))

    # Write C wrappers (optional: pass runtime c_src dir as third arg)
    c_out = Path(sys.argv[3]) if len(sys.argv) > 3 else Path("runtime/c_src")
    c_lines: list[str] = []
    emit_c_wrappers(functions, c_lines)
    (c_out / "gl_wrappers_generated.inc").write_text("\n".join(c_lines))

    print(f"Wrote {len(constants)} constants to {out_dir}/builtins_opengl_constants.rs")
    print(f"Wrote {len(functions)} function registrations to {out_dir}/builtins_opengl_functions.rs")
    print(f"Wrote {len(functions)} C wrappers to {c_out}/gl_wrappers_generated.inc")


if __name__ == "__main__":
    main()
